### California Cooperative Fisheries Research Program Survey

#### Index of Abundance
\

Since 2007, the \gls{s-ccfrp} has monitored several areas in California to evaluate the performance of \glspl{mpa} and understand nearshore fish populations [@starr_variation_2015; @wendt_collaborative_2009]. In 2017, the survey expanded beyond the four \Gls{mpa}s in central California (A&ntilde;o Nuevo, Point Lobos, Point Buchon, and Piedras Blancas) to include the entire California coast. Fish are collected by volunteer anglers aboard \glspl{cpfv} guided by one of the following academic institutions based on proximity to fishing location: Humboldt State University; Bodega Marine Laboratories; Moss Landing Marine Laboratories; Cal Poly San Luis Obispo; University of California, Santa Barbara; and Scripps Institution of Oceanography. 

Surveys consist of fishing with hook-and-line gear for 30-45 minutes within randomly chosen 500 by 500 m grid cells within and outside \glspl{mpa}. Prior to 2017, all fish were measured for length and released or descended to depth; since then, some were sampled for otoliths and fin clips.

The CCFRP Hook and Line survey is one the longest fishery-independent time series available `r area` for nearshore rockfish, having occurred annually between 2007-2022. See the [CCFRP Index of Abundance](#ccfrp-index) appendix section for details on the data filtering, processing, and model selection for these data. The estimated index of abundance was weighted based sample locations outside (reference) and inside MPAs (73 and 80 percent of areas open to fishing in the north and south, respectively, see [CDFW ROV](cdfw-rov-index) appendix for additional information about the development of rocky habitat estimates). Interpreted bathymetry classifying substrate as rock or sand is available at high resolution for state waters north of Point Conception, but is not complete for southern California (Figure \ref{ccfrp-map}). The estimated index of abundance was variable but generally flat between 2007-2016, increased in 2017 when sampling locations expanded across the northern coast with an increasing trend up until 2020, and slightly declined in the final two years in the dataset (Figure \ref{fig:ccfrp-index-main}). To account for the range expansion of this survey in areas with potentially larger `r spp` and/or areas with lower fishing pressure starting in 2017, a time block in selectivity was assumed in the model.  


#### Composition Data
\ 

Length measurements were available for 2007-2022 from the CCFRP survey `r area` and age data were collected between 2017-2022 (Table \ref{tab:ccfrp-samps}). The length data by designation, MPA and Reference, were weighted based on the estimated rocky habitat within each designation north of Point Conception (80 percent of areas open to fishing). The lengths observed by the survey ranged between 25-50 cm across the sample years with the mean length observed ranging between 33-40 cm (Figures \ref{fig:ccfrp-len-data} and \ref{fig:ccfrp-mean-len-data}). The survey collected age data from a subset of fish sampled between 2017-2022 (Figure \ref{fig:ccfrp-age-data}). The read ages from these sampled fish ranged between 2-33 years of age.