### California Department of Fish and Wildlife Remotely Operated Vehicle Survey

#### Index of Abundance 
\

The California Department of Fish and Wildlife (CDFW), in collaboration with Marine Applied Research and Exploration (MARE), have been conducting remotely operated vehicle (ROV) surveys along the California coast in Marine Protected Areas (MPAs) and reference sites adjacent to them since 2004 for the purposes of long-term monitoring of changes in size, density (fish/square meter) and length of fish and invertebrate species along the California coast. Surveys of the entire coast have now been undertaken twice, each taking three years to complete, 2014-2016 and again in 2019-2021. The survey conducted multiple 500 meter transects across rocky reef survey sites. Sample sites were selected by first randomly selecting the deepest transect at a given site, then selecting transects on a constant interval into shallower depths. Transects were designed to be oriented parallel to general depth contours, though they were carried out using a fixed bearing that crossed depths in some cases.

The data were explored using a super year approach where the central years, 2015 and 2020, were designated as the super year and the data were split north and south of Point Conception. The effort of the survey was split roughly equally between sites that were within MPAs or areas open to fishing (referred to as "Reference") with sampling across most sites (termed "MPA group") within each super year. The number of transects and the number of `r spp` by site and super year are shown in Table \ref{tab:rov-obs} with the number of observations across all years by location shown in Figure \ref{fig:rov-obs-loc}.  The trend in the calculated catch-per-unit-effort based on the data alone was highly variable across sampling locations and by MPA or Reference area (Figure \ref{fig:rov-raw-cpue}).   

CDFW provided an initial analysis of the CDFW ROV survey data which helped in determination of which modeling approaches would be considered for these data. The final selected model assumed a negative binomial error structure with covariates for super year, site designation (MPA or Reference), and super year site designation interaction. The estimated index of abundance was weighted based on the proportion of hard substrate either in MPA (20 percent) or Reference (80 percent) areas in California `r area`. The weighted index of abundance increases between the two super years 2015 and 2020 (Figure \ref{fig:rov-index-main}). Details regarding the index of abundance, sample sizes, and model selection can be found in the Appendix Section \ref{cdfw-rov-index}.

#### Composition Data
\

CDFW provided annual fish length measurements made from images taken with stereo-cameras in 2014, 2015, 2016, 2019, 2020, and 2021 (Figure \ref{fig:rov-len}). The ROV was equipped with two locally recorded stereo cameras mounted in a fixed orientation in parallel with the primary forward-facing camera used for navigation, identification and enumeration. Paired stereo video cameras were calibrated to provide accurate feature measurements by MARE prior to in-field data collection. Fish length was determined based on a photogrammetric intersection to calculate 3D coordinates from measured image coordinates to measure fork length to the nearest millimeter. Processors selected two 3D points, fish head and tail, on both time-synced port and starboard stereo images. Processors made note of an generated precision value that was computed alongside each measurement. The software then computed the Euclidean distance between the two 3D points to give a length measurement. Sizes were rounded to the nearest centimeter. The precision of estimates was determined and represents the repeatability and geometric quality of a measurement, and is dependent upon the location of the individual in the camera view and the clarity of the point measured. Precision values greater than 10 mm were recorded in the database alongside measurements, as precision values less than 10 mm meant measurements were deemed fully repeatable. Fish observations from initial species scoring were marked “not sizable” if the nose/tail of the fish was cut off in either stereo view, the fish was missing in one view, or the orientation of the fish obscured measurement or produced an extreme precision measurement. Fish were marked “not visible” if the fish was not visible in either the port or starboard image. Fish marked “not sizable” and “not visible” were removed from the final data set submitted by CDFW.


Explorations around how to use the length data within the base model were conducted (super period, combined externally into two years, by year). These explorations indicated similar fit to these data across the alternative approaches and entering them by year was selected in order to understand the fit to these data relative to the model expectations by year. The length data were weighted by MPA/Reference area and were grouped by the collection year (Figures \ref{fig:rov-len-data} and \ref{fig:mean-rov-len-data}). The input sample size was set equal to the weighted number of unique transects `r area`.  