## Base Model Results

The base model described here is only for the portion of the `r spp` stock in California from Point Conception, \PtC to the California/Oregon border, \CAOR  Descriptions of the summed biomass and stock status for the California stock of `r spp` are described in later sections.  

The base model parameter estimates along with approximate asymptotic standard errors are shown in Table \@ref(tab:params) and the likelihood components are shown in Table \ref{tab:north-likes}. Estimates of derived reference points and approximate 95 percent asymptotic confidence intervals are shown in Table \ref{tab:north-reference}. Estimates of stock size and status over time are shown in Table \ref{tab:north-timeseries}. 

The full r4ss plotting output is available in the supplementary material on the [Pacific Fishery Management Council website](pcouncil.org).

### Parameter Estimates

Estimated parameter values are provided in Table \ref{tab:params}. The log($R_0$) was estimated at `r round(model$parameters[model$parameters$Label == 'SR_LN(R0)', 'Value'], 2)`. 

The northern California base model estimated reasonable growth parameters for $k$ and lengths at age 2 and age 20 for males and females. The estimates differed from those estimated externally, which was not unexpected given the lack of consistent age data across fleets and years. The direct estimation of male $L_{age=2}$ = 12 cm was reasonable compared to female  $L_{age=2}$ = 14.6 cm.  While $k$ was estimated larger for males (0.20 yr^-1^) than females (0.15 yr^-1^), female $L_{age=20}$ of 48.3 cm was larger than males at 46.4 cm. These results are consistent with other studies that have looked at sex-specific growth in copper rockfish and similar to estimates from the southern California pre-STAR base model.


Length-based selectivity curves were estimated for the fishery and survey fleets, and age-based selectivity of 1.0 starting at age 1 for the growth fleet. Model explorations included parameterizing the fleets with double normal selectivity. Selectivity of the commercial dead fleet and the CDFW ROV survey were consistently estimated as asymptotic through base model development and were simplified to two parameter logistic selectivity in the base model. Peak selectivity for the commercial dead fleet was estimated at 34 cm, and 32 cm for the ROV survey. Plots of the estimated selectivities are shown in Figure \ref{fig:est-selex}. 

Length-based selectivity curves were estimated for the fishery and survey fleets, and age-based selectivity of 1.0 starting at age 1 for the growth fleet. Model explorations included parameterizing the fleets with double normal selectivity. Selectivity of the commercial dead fleet and the CDFW ROV survey were continually estimated as asymptotic through base model development and were simplified to two parameter logistic selectivity in the base model. Peak selectivity for the commercial dead fleet was estimated at 34 cm and 32 cm for the CDFW ROV survey. Plots of the estimated selectivities are shown in Figure \ref{fig:est-selex}. 


The commercial live fishery selectivity was estimated in two blocks of time; `r startyr` - 2010 and 2011 - `r endyr`. The block in selectivity was included to capture a shift from asymptotic selectivity prior to 2011 to the selection of plate-sized (approx. 2 pounds) fish preferred in the live-fish fishery (Figure \ref{fig:com-live-len-data}). Both recreational fleets were fit to the same three time blocks. From 1916-2001, peak selectivity was estimated around 36 cm with selectivity decreasing for larger fish; dome-shaped selectivity was estimated from  2002-2016 representing the years the fishery was restricted to shallower depths, and asymptotic selectivity starting in 2017 when the fishery gained access to deeper depths. The two estimated PR fleet selectivities were both dome-shaped with the wider peak selectivity estimated in 2017-2022 representing the change in depth regulations.

The CCFRP survey estimated peak selectivity at 33 cm in both time blocks with the first time block estimating decreased selectivity of larger fish. The survey expanded to northern California in 2017 where larger copper rockfish were observed and estimated asymptotic selectivity for fish larger than 33 cm.

The catchability for each of the surveys was analytically solved comparing observed to expected vulnerable biomass across all years. The analytical values for catchability were small given the survey methodologies and are reported in Table \ref{tab:params} in log-space.  Additional fishery and survey index variability were added directly to each year's input standard deviation for the were estimated within the model. The model estimated the largest added variance of `r round(model$parameters[model$parameters$Label == "Q_extraSD_Rec_Private(4)", 3], 3)` for the recreational PR fishery index, the survey with the largest samples size. In contrast the model estimated only limited additional variability in order to fit the recreational CRFS CPFV fishery index (`r round(model$parameters[model$parameters$Label == "Q_extraSD_CRFS_CPFV(8)", 3], 3)`). The model fit the trend in the CCFRP survey with added variance estimated to fit the time series of 
 `r round(model$parameters[model$parameters$Label == "Q_extraSD_CCFRP(5)", 3], 3)`, while the model added 
  `r round(model$parameters[model$parameters$Label == "Q_extraSD_Deb_CPFV(7))", 3], 3)` and still did not fit the trend in the index. The model fit the CDFW ROV survey index well and estimated a small added variance of  `r round(model$parameters[model$parameters$Label == "Q_extraSD_CDFW_ROV(6)", 3], 3)`.

The estimated annual recruitment and recruitment deviations are shown in  Figures \ref{fig:recruits} and \ref{fig:rec-devs}. The bias adjustment applied to the annual recruitment deviations across time is shown in Figure \ref{fig:bias-adjust}. Strong recruitment events are estimated to have occurred in 1966-1967, 2007 and 2017 with the years of lowest estimated recruitment being 1979 and 1980. The uncertainty in recruitment deviations is highest for the first two years, 1970 and 1971, and relatively consistent for the remainder of the time series. There is limited information in the data on recruitment variability from the available data.  During model explorations, the recruitment deviations were most sensitive to the removal of the available age and fishery index data.  

Recruitment is estimated based on the spawner-recruit curve in 2021 and 2022  (Figure \ref{fig:bh-curve}). The recruitment bias adjustment was applied within the model across years is shown in Figure \ref{fig:bias-adjust}.

### Fits to the Data

#### Fits to length and age composition

Fits to the length data are shown based on the Pearson residuals-at-length, the annual mean lengths, and aggregated length composition data for the commercial and recreational fleets. Annual length composition fits are shown in the Appendix, Section \ref{detailed-fit-comps}.  Aggregate fits by fleet are shown in Figure \ref{fig:len-agg-fit}.  

The aggregated lengths for the commercial dead fleet reflected a wide selection across sizes, with the model under-predicting the selection for both small males and females. The majority of the length data for the commercial dead fleet consisted of unsexed fish with sex-specific lengths available from 1980, 1984, 1999, and 2019-2022. The aggregate length composition fit well with the asymptotic selectivity curve for the commercial dead fleet. Multiple sensitivities were conducted to explore alternative parameterization of commercial dead fleet selectivity. The Pearson residuals for the commercial dead fishery length data are shown in Figure \ref{fig:com-dead-pearson}.  The commercial mean lengths of unsexed fish were generally stable between 1990 - 2019 and decreased to smaller sizes from 2019 - 2022, with high uncertainty in the mean lengths of unsexed fish in 2022 (Figure \ref{fig:com-dead-mean-len-fit}). The observations of larger fish, greater than 40 cm, are minimally greater than the model expectations after 2010. A limited number of ages from the commercial dead fleet were available from 2019-2022.  The model estimated mean conditional age was within the bounds of uncertainty, but was not well fit (Figure \ref{fig:com-dead-mean-age}).

Starting in 2010, the commercial live fleet length data shifts to smaller fish with observations greater than model expectations for fish between 25 - 30 cm. All available lengths for the commercial live fleet were from unsexed fish and the aggregated length data were fit relatively well given the change in selectivity in 2011. There were no ages available from the commercial live fleet.  The Pearson residuals for the commercial dead fishery length data area shown in Figure \ref{fig:com-live-pearson}.  The means of observed commercial lengths of unsexed fish were not stable prior to 2011 (Figure \ref{fig:com-dead-mean-len-fit}). From 2011-2022 the mean lengths of fish in the live fishery are relatively stable, with a notable decrease in 2016.


The length compositions for the recreational CPFV fleet were relatively well fit throughout the time series, except for a few years where a number of fish in a single size class were observed that the model did not expect given the selectivity.  The Pearson residuals do not show an indication of any strong year classes from the available lengths (Figure \ref{fig:rec-cpfv-pearson}). The mean length of observed unsexed fish from the CPFV fleet was fit relatively well, indicating a slight increase in mean size around 2000, a decrease from 2007-2011 and a slight increase again from 2013-2018  (Figure \ref{fig:rec-cpfv-mean-len-fit). The number of sexed fish available from the CPFV fleet is small. The last year of data was not well fit and was estimated with high uncertainty. Age data were only available from 2022 from a combination of NMFS Cooperative Research Sampling ollections and the CDFW groundfish group. A small fraction of these fish were unsexed, and the Pearson residuals indicate these data were generally well-fit  (Figure \ref{fig:rec-cpfv-age-pearson}).

The Pearson residuals for the recreational PR length data were variable by year (Figure \ref{fig:rec-pr-pearson}). Pearson residuals were positive, with observations greater than expected, for small fish prior to 1997 and were generally variable showing no clear misfit in the model in recent years. The aggregate length composition data from the PR fleet had a slightly higher peak around 29 cm with fewer observations.  The length composition across years is fit well from 2004-2022 when CDFW implemented the CRFS sampling program.  A wide range of sizes were observed from 1959-1987 with poorer fits in years with less data such as 1989 and 1996-2002. The mean length by year for the recreational PR fleet was highly variable across years (Figure \ref{fig:rec-pr-mean-len-fit}). The implementation of the MPA network may have impacted the shift to smaller mean sizes in those years.  CDFW collected ages from the recreational PR fleet in 2022. The peak of the age distribution was underestimated by the model(Figure \ref{fig:rec-pr-age-pearson}).

The length composition fits to the recreational CPFV fleet were relatively well fit throughout the time series, except for a few years where the a number of fish in a single size class were observed that the model did not expect given the selectivity.  The Pearson residuals do not show an indication of any strong year classes from the available lengths (Figure \ref{fig:rec-cpfv-pearson}). The mean length observed, unsexed fish from the CPFV fleet was fit relatively well, indicating a slight increase in mean size around 2000, a decrease from 2007-2011 and a slight increase again from 2013-2018  (Figure \ref{fig:rec-cpfv-mean-len-fit}). The number of sexed fish available from the CPFV fleet is small and the last year of data was not well fit and estimated with high uncertainty. Only one year of age data were available, 2022, from a combination of NMFS Cooperative Research collections and the CDFW groundfish group. A small fraction of these fish were unsexed, and the Pearson residuals indicate these data were generally well-fit  (Figure \ref{fig:rec-cpfv-age-pearson}).

The Pearson residuals for the recreational PR length data are variable by year (Figure \ref{fig:rec-pr-pearson}). Pearson residuals were positive, observations greater than expected, for small fish prior to 1997 and are generally variable showing no clear misfit in the model in recent years. The aggregate length composition data from the PR fleet had a slightly higher peak around 29 cm with fewer observations.  The length composition across years is fit well from 2004-2022 when CDFW implemented the CRFS sampling program.  A wide range of sizes were observed from 1959-1987 with poorer fits in years with less data such as 1989 and 1996-2002. The mean length by year for the recreational PR fleet was highly variable across years (Figure \ref{fig:rec-pr-mean-len-fit}). The implementation of the MPA network may have impacted the shift to smaller mean size in those years.  The CDFW collected ages from the recreational PR fleet in 2022. The peak of the age distribution was underestimated by the model (Figure \ref{fig:rec-pr-age-pearson}).


The aggregated length compositions for both fishery-independent surveys, CCFRP and the CDFW ROV, were fit reasonably well with an underestimation of fish at around 40-45 cm in the ROV survey. Both of these surveys were conducted in California state waters and represent samples from inside and outside the MPAs. The annual fits to the CCFRP length data were not as well fit as other data sources in any given year, but the observation of larger fish when the survey expanded north in 2017 is pronounced. The Pearson residuals are presented in Figure \ref{fig:ccfrp-len-pearson} and exhibit no clear pattern. The model estimated mean length was increasing from 2014-2016 prior to the survey's expansion  (Figure \ref{fig:ccfrp-mean-len-fit}). The model did not fit the decrease in observed mean length in 2019, but did capture the increase in mean age in 2022. Age data were available from 2018, 2019 and 2022 from the CCFRP survey and were input as conditional age-at-length data. The data had a slightly higher proportion of older fish given  estimated growth  (Figure \ref{fig:ccfrp-age-pearson}). Of note is that all of these ages represent the time period after the survey expanded and selectivity was estimated to be asymptotic.

The length composition data for the ROV survey were available at a finer scale than the super years available for the index of abundance. Not surprisingly, the year with the most available length observations, 2021, had the best fit to the length data, although was an underestimate for fish in the 35-45  cm range. No trend was observed from the Pearson residuals (Figure \ref{fig:ccfrp-len-pearson}). The survey covered a wide range of depths and the same increasing trend in mean size as the CCFRP data was observed in the ROV survey from 2019-2021 (Figure \ref{fig:rov-mean-len-fit}).


#### Fits to Indices of Abundance
\

Fits to the indices vary in quality.  The Deb Wilson-Vandenberg onboard survey from 1988-1998 indicated a decline from 1992-1998 that was not fit well by the model.  However, this is the highest quality data source for the time period and with the added variance, the model fit was fairly flat and uninformative (Figure \@ref(fig:dwv-cpfv-index-fit)). The index spans the years where the stock biomass begins to increase, creating a conflict between the index and the population trend. The Deb Wilson-Vandenberg survey effort was concentrated in central California, similar to the area surveyed from 2007-2016 in the CCFRP survey.  

The CDFW and Cal Poly onboard index was flat from 2004-2015 and the increase in relative CPUE in the ending years, 2017-2019, represent time periods when the fishery had access to deeper water, but the increase in relative CPUE in 2016 was not due to changes in regulations (Figure \@ref(fig:crfs-cpfv-index-fit)). The model fit the ending years of data to the upper bound of the added variability.

The recreational dockside PR index showed a similar trend as the CPFV onboard index. The index was well fit during the first part of the time series when it was relatively flat (2004-2015), but the increase in relative CPUE in the ending years, 2017-2019, was not well captured by the model. Even with selectivity time blocks for these periods, the index was not fit in 2017. 


The CDFW ROV survey contained data grouped into two super years and the model estimated a relatively flat line with the added variance (Figure \ref{fig:crfs-pr-index-fit}). The CCFRP index reflects the same increase in relative CPUE in 2016 as the CPFV and PR indices, prior to the survey expansion and release of recreational depth restrictions. This index was weighted by the area within the MPAs, which exhibits an increasing trend compared to sites outside the survey at the end of the time series (Figure \@ref(fig:ccfrp-index-fit)). The fit to the early part of the time series was reasonable given the available data.  Similar to the 2019 gopher/black-and-yellow rockfish complex CCFRP survey, the lowest estimated year in the CCFRP index was 2013, which was also not fit in the 2019 gopher stock assessment.  No explanation for the decrease in relative CPUE was identified. 


### Population Trajectory in the Modeled Area

The predicted spawning output (in millions of eggs) is given in Table \ref{tab:north-timeseries} and shown in Figure \ref{fig:ssb}. The estimated spawning output decreases sharply in the late-1970s and continues to decline until reaching low levels in the late-1990s. The spawning output slowly increases between 2000 - 2010 with the rate of population growth increasing after 2011 as fish from recent years of above average recruitment begin to mature. The estimate of total biomass follows the same trend over time and is shown in Figure \ref{fig:tot-bio}. The estimated spawning output relative to unfished equilibrium spawning output for the sub-area `r area` reached a minimum of 0.17 in 1994 and then increased over the recent time period, with an ending year estimate of 0.52 in 2022 (Figure \ref{fig:depl}).


### Population Trajectory for the Stock

```{r, echo=FALSE, results='asis'}

filein = file.path(doc_dir, "shared_text",'33_population.Rmd')
read_child(filein)
```

<!--
### Reference Points

Reference points were calculated using the estimated selectivities and the catch distribution among fleets in the most recent year of the model, `r endyr`. Sustainable total yield (landings plus discards) was `r round(model$derived_quants[model$derived_quants$Label == 'Dead_Catch_SPR', 'Value'], 2)` mt when using an $SPR_{50\%}$ 
reference harvest rate. The spawning output equivalent to 40% of the unfished level ($SB_{40\%}$) was `r round(model$derived_quants[model$derived_quants$Label == 'SSB_Btgt', 'Value'], 0)` 
million eggs. 

The `r endyr` spawning biomass relative to unfished equilibrium spawning biomass is just below the target of 40% of unfished levels (Figure \@ref(fig:depl)). The relative fishing intensity, $(1-SPR)/(1-SPR_{50\%})$, was near the management target in 2020, and has fluctuated around the target level for the past decade (Figure \@ref(fig:1-spr) and \@ref(fig:phase)). 

Table \@ref(tab:north-reference) shows the full suite of estimated reference points for the base model and Figure \@ref(fig:yield-north) shows the equilibrium yield curve and net production based on a steepness value fixed at `r round(model$parameters[model$parameters$Label == "SR_BH_steep","Value"], 2)`.
=======
Table \@ref(tab:north-reference) shows the full suite of estimated reference points for the base model and Figures \@ref(fig:yield-north) shows the equilibrium yield curve and net production based on a steepness value fixed at `r round(model$parameters[model$parameters$Label == "SR_BH_steep","Value"], 2)`.

-->
