## Model Diagnostics

### Convergence

Proper convergence was determined by starting the minimization process from dispersed values of the maximum likelihood estimates to determine if the model found a better minimum. Starting parameters were jittered using the jitter function built into Stock Synthesis, using jitter input of 0.10. This was repeated 100 times with 89 out of 100 runs returning to the base model likelihood. A better, lower negative log-likelihood, model fit was not found. Through the jittering and likelihood profiles, we are confident that the base model, as presented, represents the best fit to the data given the assumptions made. There were no difficulties in inverting the Hessian to obtain estimates of variability, although much of the early model investigation was done without attempting to estimate a Hessian.

### Sensitivity Analyses

Sensitivity analyses were conducted to examine the relative influence of specific changes to data inputs and model structural assumptions to further address uncertainty associated with the base model estimates and derived management quantities.  The majority of the sensitivity models are the result of a single change relative to the base model (i.e., they are not the result of cumulative changes such as the modeling approach used with the bridging analysis). Comparisons of likelihood values and estimates of key parameters from the sensitivity analysis are shown in Tables \ref{tab:sensitivities-1}-\ref{tab:sensitivities-3}. Comparison of all sensitivities relative to the base model is shown in Figure \ref{fig:sens-all} with Figures \ref{fig:sens-ssb-1}-\ref{fig:sens-depl-3} showing the change in spawning output and the relative spawning output trajectories. Many additional sensitivity runs were explored during development and testing of the base model. This section focuses on the main data and structural sensitivity model runs and includes the following:

Structural Sensitivities

\begin{enumerate}
   
  \item  Estimate natural mortality ($M$) for each sex.
  
  \item Estimate steepness ($h$).
  
  \item Estimate $M$ for each sex and $h$.
  
  \item Remove added variance from all fishery-dependent and -independent indices of abundance (fixed equal to 0.01).
  
  \item Fix recruitment to be equal to the stock-recruitment curve (no recruitment deviations).
  
  \item Apply Dirichlet data weights.
  
  \item Apply McAllister-Ianelli data weights.

\end{enumerate}

Data Sensitivities

\begin{enumerate}
   
  \item Reduce the CPFV and PR catch between 1970-1982 to half of each fleet's average catch for that period of time.
  
  \item Move the historical CPFV ages into the growth fleet.
  
  \item Retain only length data within the model (no indices or ages) and fix growth at the estimates.
  
  \item Remove the CPFV cooperative collection ages in 2022.
  
  \item Remove all age data and fix growth at the estimates.
  
  \item Remove the CCFRP Hook and Line survey data (index, lengths, and ages).
  
  \item Remove the CDFW ROV survey data (index and lengths).
  
  \item Remove both the CCFRP Hook and Line and CDFW ROV survey data (indices, lengths, and ages).
  
  \item Remove the CRFS CPFV index of abundance.
  
  \item Remove the Deb-Wilson Vandenberg CPFV index of abundance.
  
  \item Remove the CRFS PR index of abundance.
  
\end{enumerate}


Across all the sensitivities conducted, only a subset resulted in distinct changes in the model estimates and the discussion here will focus on the sensitivities that were identified in Figure \ref{fig:sens-all}. For the sensitivity without recruitment deviations and predicting recruitment directly from the stock-recruitment curve, the estimate of initial unfished recruitment ($R_0$) increased and the contribution of the length contributed to the increased model likelihood (Table \ref{{tab:sensitivities-1}, Figures \ref{fig:sens-ssb-1} and \ref{fig:sens-depl-1}).  In addition, the model estimated a 63% increase in the 2023 spawning biomass.

The sensitivities estimating natural mortality and/or steepness all resulted in a decreased 2023 spawning biomass. In both sensitivities where natural mortality was estimated, the estimates were considered too low for a rockfish with a maximum age of less than 55.  The model estimating only steepness also resulted in an estimate of less than half the prior (Table \ref{tab:sensitivities-1}).  The models estimating natural mortality and/or steepness are the only models that fit a flat, uninformative trend to Deb Wilson-Vandenberg's onboard data.  The models with estimated natural mortality and/or steepness estimated a more depleted stock. 

Across all the sensitivities conducted only a subset resulted in distinct changes in the model estimates and the discussion here will focus on the sensitivities that were identified in Figure \ref{fig:sens-all}. The sensitivity without recruitment deviations and recruitment was predicted directly from the stock-recruitment curve, the estimate of initial unfished recruitment ($R_0$) increased and the contribution of the length contributed to the increased model likelihood (Table \ref{tab:sensitivities-1}, Figures \ref{fig:sens-ssb-1} and \ref{fig:sens-depl-1}).  In addition, the model estimated a 63% increase in the 2023 spawning biomass.

The sensitivities estimating natural mortality and/or steepness all resulted in a decreased 2023 spawning biomass. In both sensitivities where natural mortality was estimated, the estimates were considered too low for a rockfish with a max age of less than 55.  The model estimating only steepness also resulted in an estimate of less than half the prior (Table \ref{tab:sensitivities-1}).  The models estimating naturaly mortality and/or steepness are the only models that fit a flat, uninformative trend to Deb Wilson-Vandenberg's onboard data.  The models with estimated natural mortality and/or steepness estimated a more depleted stock. 


The leave one out sensitivities provide insight into the contribution of each data stream to the base model.  While the Deb Wilson-Vandenberg index was not fit well by the model, the removal of the index results in the same directional increase in estimated 2023 spawning biomass as the removal of the more recent onboard observer CPFV survey (Figure \ref{fig:sens-all}).  


The sensitivity of the reduced recreational catches from 1970-1982 addresses a question of uncertainty in the -@ralston_documentation_2010 reconstruction. Information on the minor nearshore rockfish species was more limited when the catch reconstruction was developed and the estimates of catch during this time period in the north was estimated at twice that in southern California.  The sensitivity produced the expected shift to a smaller estimated stock size.  

The sensitivity of the the reduced recreational catches from 1970-1982 address a question of uncertainty in the Ralston et al. [-@ralston_documentation_2010]. Information on the minor nearshore rockfish species was more limited when the catch reconstruction was developed. and the estimates of catch during this time period in the north was estimated at twice that in southern California.  The sensitivity produced the expected shift to a smaller estimated stock size.  



### Retrospective Analysis

A five-year retrospective analysis was conducted by successively removing years of data ranging from 2017 - 2021 (i.e., "Data -1 Years" corresponds to data through 2021). The estimated spawning output for all retrospectives was lower at the start of the time series and lower for the final model years (Figure \ref{fig:retro-ssb}). The retrospective model through 2020 was very similar to the base model. Removing all five years of data produces a more similar estimate in spawning biomass than removing three years of data, suggesting data in the most recent three years provide information.  The recent years of positive recruitment deviations were largest in the base model. The estimates of relative spawning output to unfished were similar between the base model and the model with data through 2017, with intermediate peels of the data estimating a more depleted stock  (Figure \ref{fig:retro-depl}). The estimated relative spawning output to unfished in the retrospectives were within the bounds of uncertainty in the base model.

A five-year retrospective analysis was conducted by successively removing years of data ranging from 2017 - 2021 (i.e., "Data -1 Years" corresponds to data through 2021). The estimated spawning output for all retrospectives was lower at the start of the time series and and lower for the final model years (Figure \ref{fig:retro-ssb}). The retrospective model through 2020 was very similar to the base model. Removing all 5 years of data produces a more similar estimate in spawning biomass than removing three years of data, suggesting data in the most recent three years provide information.  The recent years of positive recruitment deviations were largest in the base model. The estimates of relative spawning output to unfished were similar between the base model and the model with data through 2017, with intermediate peels of the data estimating a more depleted stock  (Figure \ref{fig:retro-depl}). The estimated relative spawning output to unfished in the retrospective were within the bounds of uncertainty in the base model.


### Likelihood Profiles

Likelihood profiles were conducted for $R_0$, steepness, and sex-specific natural mortality values separately. These likelihood profiles were conducted by fixing the parameter at specific values and estimated the remaining parameters based on the fixed parameter value.

The negative-log-likelihood was minimized at a log($R_0$)value of `r round(model$estimated_non_dev_parameters[rownames(model$estimated_non_dev_parameters) == "SR_LN(R0)", "Value"], 2)` (Figure \ref{fig:r0-profile}). The likelihood profile was most informed by the recruitment and length components of the  likelihood. The length composition supported lower values of $R_0$ and the age composition supported larger values of $R_0$ across the values profiled. Across the values of log($R_0$) profiled, the range of end year spawning output was larger than the estimates of unfished biomass (Figure \ref{fig:r0-ssb}).  Ending year depletion ranged from 37-107 percent of unfished biomass (Figure \ref{fig:r0-depl}). 


The majority of data types did not provide  consistent information on the estimate of steepness given the data included in the base model (Figure \ref{fig:h-profile}). As with the profile over $R_0$, the contribution of recruitment to the likelihood was the most informative for steepness. The two recreational length composition components of the likelihood support a higher estimate of steepness than the the minimum idenfitied by the profile (approx. 0.45). The estimated value was much lower than the fixed value in the base model (0.72).  The model responded as expected to the values over which steepness was profiled, with high values of $h$ resulting in both a higher ending spawning output and a less depleted stock (Figures \ref{fig:h-ssb} and \ref{fig:h-depl}). The ending year depletion ranged from 10-71 percent, a smaller range than the profile over $R_0$.  

The profile over female natural mortality suggested the negative log-likelihood was minimized at around 0.095 yr^-1^, which was lower than the fixed value of 0.108 yr^-1^ in the base model (Figure \ref{fig:m-profile}), and the chnage in likelihood was less than two.  The length component of the likelihood provided the most influential information in estimation of natural moratlity. Within the length likelihood component, the recreational CPFV length supported the lower value of natural mortality whereas the length data from CCFRP and both commercial fleets supported higher values of natural mortality.  The profile over female natural mortality had an overall smaller impact on the end year spawning biomass (Figure \ref{fig:m-ssb}).  However, the end year estimates of depletion ranged from 24-67 percent (Figure \ref{fig:m-depl}).  This range is outside the 95% asymptotic interval from the base model on the lower end, but is within the bounds for the higher values of natural mortality in the profile. 

### Historical Analysis

The estimated spawning output from both the 2013 and 2021 assessments for the portion of `r spp` `r area` compared to the base model are shown in Figures \ref{fig:comp-assess-sb} and \ref{fig:comp-assess-depl}. The model structure and the approach used in the 2013, index-based data-moderate assessment using Extended-Depletion-Based Stock Reduction Analysis, was significantly different from both the 2021 and this assessment. While the estimates from the 2013 model were converted to spawning output for this comparison, the assumed growth, maturity, and selectivity in that assessment resulted in a significantly larger estimate of spawning output with a less depleted population. The estimated scale of the population and relative fraction of spawning output among the 2021 assessment and this base model were consistent despite the number of additional data sources, changes in biology (estimated vs. fixed at external estimates), and recruitment dynamics (estimation of annual recruitment deviations in the base model which fixed to 0 in the 2021 assessment).   

The majority of data types did not provide  consistent or information on the estimate of steepness given the data included in the base model (Figure \ref{fig:h-profile}). As with the profile over $R_0$, the contribution of recruitment to the likelihood was the most informative for steepness. The two recreational length composition components of the likelihood support a higher estimate of steepness than the the minimum identified by the profile (approx. 0.45). The estimated value was much lower than the fixed value in the base model (0.72). The  The model responded as expected to the values over which steepness was profiled, with high values of $h$ resulting in both a higher ending spawning out and a less depleted stock (Figures \ref{fig:h-ssb} and \ref{fig:h-depl}). The range of ending year depletion ranged from 10-71 percent, a smaller range than the profile over $R_0$.  

The profile over female natural mortality suggested the negative log-likelihood was minimized data around 0.095 yr^-1^, which was lower than the fixed value of 0.108 yr^-1^ in the base model (Figure \ref{fig:m-profile}), and the change in likelihood was less than two.  The length component of the likelihood provided the most influential information in estimation of natural mortality. Within the length likelihood component, the recreational CPFV length supported the lower value of natural mortality whereas the length data from CCFRP and both commercial fleets supported higher values of natural mortality.  The profile over female natural mortality had an overall smaller impact on the end year spawning biomass (Figure \ref{fig:m-ssb}).  However, the end year estimates of depletion ranged from 24-67 percent (Figure \ref{fig:m-depl}).  This range is outside the 95% asymptotic interval from the base model on the lower end, but but within the bounds for the higher values of natural mortality in the profile. 

### Historical Analysis

The estimated spawning output from the 2021 assessments for the portion of `r spp` `r area` compared to the base model are shown in Figures \ref{fig:comp-assess-sb} and \ref{fig:comp-assess-depl}. The results from the 2013 assessment are not included since that assessment modeled the area north of Point Conception to the Washington/Canadian border as a single area. The estimated scale of the population and relative fraction of spawning output between the 2021 assessment and this base model were somewhat consistent (i.e., the 2021 estimated values within the uncertainty interval estimated by the base model) despite the number of additional data sources, changes in biology (estimated vs. fixed at external estimates), and recruitment dynamics (estimation of annual recruitment deviations in the base model which fixed to 0 in the 2021 assessment). However, the 2021 assessment estimate a more severe reduction in the spawning output with the estimated relative spawning output less than the estimate from the base model.b   


