\clearpage
# Figures

<!-- ====================================================================== --> 
<!-- *******************    Assessment Map      *************************** --> 
<!-- ====================================================================== --> 

```{r, results = 'asis'}
add_figure(
filein = file.path(doc_dir, "shared_figures", "map.png"), 
caption = "Map of management area and the 2023 assessments areas for copper rockfish",
label = 'ca-map')
```


<!-- ====================================================================== -->  
<!-- ****************** Catches Used in the Model ************************* --> 
<!-- ====================================================================== -->  

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "catch2 landings stacked.png"), 
caption = "Landings by fleet used in the base model where catches in metric tons by fleet are stacked",
label = 'catch')
```	

<!-- ====================================================================== --> 
<!-- ******************* Data Used in the Model *************************** --> 
<!-- ====================================================================== --> 

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "data_plot.png"), 
caption = "Summary of data sources used in the base model",
label = 'data-plot')
```	

<!-- ======================================================= -->
<!-- *************** Commercial Data *********************** --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_bubflt1mkt0.png"), 
caption = "Length composition data from the commercial dead fleet",
label = 'com-dead-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_data_weighting_TA1.8_Commercial_Dead.png"), 
caption = "Mean length for commercial dead fleet with 95 percent confidence intervals",
label = 'mean-com-dead-len-data')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_condAALdat_bubflt1mkt0.png"), 
caption = "Conditional age-at-length composition data from the commercial dead fleet",
label = 'com-dead-age-data')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_bubflt2mkt0.png"), 
caption = "Length composition data from the commercial live fleet",
label = 'com-live-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_data_weighting_TA1.8_Commercial_Live.png"), 
caption = "Mean length for commercial live fleet with 95 percent confidence intervals",
label = 'mean-com-live-len-data')
```


<!-- ======================================================= -->
<!-- ************ Recreational Indices ********************* --> 
<!-- ======================================================= -->


```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "rec_indices", "mrfss_cpfv_dockside", "north",  "forSS", "Index.png"), 
caption = "Estimated annual index of abundances for the CPFV fleet based on MRFSS survey data.",
label = 'mrfss-index-main')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "rec_indices", "debwv_cpfv_onboard",  "delta_lognormal_main_effects", "Index.png"), 
caption = "Estimated annual index of abundances for the CPFV fleet based on the Deb Wilson-Vandenberg survey data.",
label = 'dwv-index-main')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "rec_indices", "crfs_cpfv_onboard", "north",  "area_weighted", "Index.png"), 
caption = "Estimated annual index of abundances for the CPFV fleet based on CRFS survey data.",
label = 'crfs-index-main')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "rec_indices", "crfs_pr_dockside", "north",  "rm_last2yrs_area_weighted", "Index.png"), 
caption = "Estimated annual index of abundances for the CPFV fleet based on CRFS survey data.",
label = 'crfs-pr-index-main')
```


<!-- ======================================================= -->
<!-- ************* Recreational Data *********************** --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_bubflt3mkt0_page2.png"), 
caption = "Length composition data from the recreational CPFV fleet",
label = 'rec-cpfv-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_data_weighting_TA1.8_Rec_CPFV.png"), 
caption = "Mean length for recreational CPFV fleet with 95 percent confidence intervals",
label = 'mean-rec-cpfv-len-data')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_condAALdat_bubflt3mkt0.png"), 
caption = "Conditional age-at-length composition data from the recreational CPFV fleet",
label = 'rec-cpfv-caal-data')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_agedat_data_weighting_TA1.8_Rec_CPFV.png"), 
caption = "Mean age for recreational CPFV fleet with 95 percent confidence intervals",
label = 'mean-rec-cpfv-age-data')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "ages", "plots", "coop_crfs_length_comparison.png"), 
caption = "Comparison of all length collected by the CRFS sampling program for the CPFV fleet to the lengths from the fish with ages from the cooperative sampling program. The length distributions in the area north of Point Conception are in general agreement while the distribution of lengths collected by this program does not align with the length samples from CRFS.",
label = 'coop-len-comparison')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_condAALdat_bubflt4mkt0.png"), 
caption = "Conditional age-at-length data for recreational PR collected in 2022",
label = 'rec-pr-caal-data')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_flt4mkt0_page2.png"), 
caption = "Length composition data from the recreational PR fleet",
label = 'rec-pr-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_data_weighting_TA1.8_Rec_PR.png"), 
caption = "Mean length for recreational PR fleet with 95 percent confidence intervals",
label = 'mean-rec-pr-len-data')
```

<!-- ======================================================= -->
<!-- *************  Add Survey Locations Map  ************** --> 
<!-- ======================================================= -->


```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "survey_indices", "plots", "north_survey_locations_designation.png"), 
caption = "Sample locations by each of the fishery-independent data sources used in the base model with indices of abundance, lengths, and ages if collected.",
label = 'survey-locations')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "survey_indices", "plots", "north_survey_locations.png"), 
caption = "Sample locations by area, areas open to fishing (reference) and MPAS, for each of the fishery-independent data sources used in the base model with indices of abundance, lengths, and ages if collected.",
label = 'ref-mpa')
```


<!-- ======================================================= -->
<!-- ***************     CCFRP           ******************* --> 
<!-- ======================================================= -->


```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "survey_indices", "ccfrp", "north", "area_weighted", "Index.png"), 
caption = "Estimated index of abundance from the CCFRP survey",
label = 'ccfrp-index-main')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_bubflt5mkt0.png"), 
caption = "Length composition data from the CCFRP survey",
label = 'ccfrp-len-data')
```



```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_data_weighting_TA1.8_CCFRP.png"), 
caption = "Mean length for the CCFRP survey with 95 percent confidence intervals",
label = 'ccfrp-mean-len-data')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_condAALdat_bubflt5mkt0.png"), 
caption = "Conditional age-at-length data from the CCFRP survey",
label = 'ccfrp-age-data')
```


<!-- ======================================================= -->
<!-- ***************    CDFW ROV         ******************* --> 
<!-- ======================================================= -->


```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(data_dir, "survey_indices", "rov", "plots", "rov_transect_collapsed_copper_north_protection_count.png"), 
caption = "The location and size of observations across all years and transects.",
label = 'rov-obs-loc')
```



```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(data_dir, "survey_indices", "rov", "plots", "north_raw_cpue_by_mpa_group.png"), 
caption = "The trend of the calculated CPUE by each MPA and Reference group.",
label = 'rov-raw-cpue')
```


```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(data_dir, "survey_indices", "rov", "glm_negbin_north_designation_depth", "Index.png"), 
caption = "The estimated weighted relative index of abundance.",
label = 'rov-index-main')
```


```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(data_dir, "survey_indices", "rov", "plots", "rov_length_by_area_designation.png"), 
caption = "The distribution of lengths across all years for MPA and Reference area north and south of Point Conception.",
label = 'rov-len')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_flt6mkt0.png"), 
caption = "Length composition data from the CDFW ROV survey",
label = 'rov-len-data')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_data_weighting_TA1.8_CDFW_ROV.png"), 
caption = "Mean length for CDWF ROV survey with 95 percent confidence intervals",
label = 'mean-rov-len-data')
```


<!-- ======================================================= -->
<!-- ***************  NWFSC WCGBT Survey  ****************** --> 
<!-- ======================================================= -->



<!-- ======================================================= -->
<!-- ***************  Growth  ****************** --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "ages",  "plots", "south_growth_length_comparison.png"), 
caption = "Length distribution of fish by collection source that were used as conditional age-at-length data in the growth fleet.",
label = 'growth-len-dist')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "ages",  "plots", "south_growth_age_comparison.png"), 
caption = "Age distribution of fish by collection source that were used as conditional age-at-length data in the growth fleet.",
label = 'growth-age-dist')
```




<!-- ======================================================= -->
<!-- ***************  life history  ************************ --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
add_figure(
filein = file.path(doc_dir, "shared_figures", "copper_length_by_half_month.png"), 
caption = "Distribution of YOY copper rockfish lengths from fish genetically identified from D. Baetscher.",
label = 'copper-smurf-length')
```



<!-- ======================================================= -->  
<!-- ******************   Biology  ************************* --> 
<!-- ======================================================= -->  



```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "bio6_maturity.png"), 
caption = "Maturity as a function of length",
label = 'maturity')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "bio9_fecundity_len.png"), 
caption = "Fecundity as a function of length",
label = 'fecundity')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "wcgbt", "plots", "length_fraction_female.png"), 
caption = "Fraction of each sex by length by the NWFSC WCGBT survey",
label = 'frac-sex-len')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "biology", "plots", "Length_Weight_All.png"), 
caption = "Estimated weight-at-length",
label = 'weight-length')
```



```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "ages", "ageing_error", "B0_S3", "Reader_1_vs_Reader_2.png"), 
caption = "Distribution of double reads between age reader 1 and 2.",
label = 'age-error-dist')
```



```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots",  "numbers5_ageerrorSD.png"), 
caption = "Ageing imprecision standard deviation of observed age in years.",
label = 'age-error')
```



```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots",  "numbers10_ageerror_matrix_1.png"), 
caption = "Distribution of observed age at true age for ageing error type 1.",
label = 'age-error-matrix')
```




<!-- ======================================================= -->  
<!-- ******************   Bridge   ************************* --> 
<!-- ======================================================= -->



```{r, results = 'asis'}
add_figure(
filein = file.path(bridge_dir, "_plots", "0_model_convert_compare2_spawnbio_uncertainty.png"),
caption = "Model version bridge comparison of estimated spawning output",
label = 'bridge-ssb')
```

```{r, results = 'asis'}

add_figure(
filein = file.path(bridge_dir, "_plots", "0_model_convert_compare4_Bratio_uncertainty.png"),
caption = "Model version bridge comparison of estimated fraction unfished",
label = 'bridge-depl')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(bridge_dir, "_plots", "full_bridge_1_compare2_spawnbio_uncertainty.png"),
caption = "Model structure and data bridging comparison of estimated spawning output",
label = 'data-bridge-ssb-1')
```


```{r, results = 'asis'}

add_figure(
filein = file.path(bridge_dir, "_plots", "full_bridge_1_compare4_Bratio_uncertainty.png"),
caption = "Model structure and data bridging comparison of estimated fraction unfished",
label = 'data-bridge-depl-1')
```




```{r, results = 'asis'}
add_figure(
filein = file.path(bridge_dir, "_plots", "full_bridge_2_compare2_spawnbio_uncertainty.png"),
caption = "Model structure and data bridging comparison of estimated spawning output",
label = 'data-bridge-ssb-2')
```

```{r, results = 'asis'}

add_figure(
filein = file.path(bridge_dir, "_plots", "full_bridge_2_compare4_Bratio_uncertainty.png"),
caption = "Model structure and data bridging comparison of estimated fraction unfished",
label = 'data-bridge-depl-2')
```


<!-- ====================================================================== -->
<!-- *********************    Priors            ********************** --> 
<!-- ====================================================================== -->

<!-- ====================================================================== -->
<!-- *********************  Model Est. Biology       ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "bio1_sizeatage.png"),
caption = "Model estimated length-at-age in the beginning of the year. Shaded area indicates 95 percent distribution of length-at-age around the estimated growth curve",
label = 'mod-est-len-age')
```

<!-- ====================================================================== -->
<!-- *********************    Selectivity            ********************** --> 
<!-- ====================================================================== -->




<!-- ======================================================= -->  
<!-- ****************** Recruitment ************************ --> 
<!-- ======================================================= -->


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "ts11_Age-0_recruits_(1000s)_with_95_asymptotic_intervals.png"), 
caption = "Estimated time series of age-0 recruits (1000s)",
label = 'recruits')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "recdevs2_withbars.png"), 
caption = "Estimated time series of recruitment deviations",
label = 'rec-devs')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "SR_curve.png"), 
caption = "Stock-recruit curve. Point colors indicate year, with warmer colors indicating earlier years and cooler colors in showing later years",
label = 'bh-curve')
```



<!-- ====================================================================== -->
<!-- *************** Fit to the Length & Age Data  ************************ --> 
<!-- ====================================================================== -->




<!-- ====================================================================== -->
<!-- ****************** Fit to the Index Data  **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "index5_logcpuefit_Rec_CPFV.png"), 
caption = "Fit to log index data on log scale for recreational (MRFSS) CPFV. Lines indicate 95% uncertainty interval around index values based on the model assumption of lognormal error. Thicker lines (if present) indicate input uncertainty before addition of estimated additional uncertainty parameter",
label = 'mrfss-cpfv-index-fit')
```




```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "index5_logcpuefit_DWV_CPFV.png"), 
caption = "Fit to log index data on log scale for Deb Wilson-Vandenberg CPFV survey. Lines indicate 95% uncertainty interval around index values based on the model assumption of lognormal error. Thicker lines (if present) indicate input uncertainty before addition of estimated additional uncertainty parameter",
label = 'dwv-cpfv-index-fit')
```




```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "index5_logcpuefit_CRFS_CPFV.png"), 
caption = "Fit to log index data on log scale for CRFS CPFV survey. Lines indicate 95% uncertainty interval around index values based on the model assumption of lognormal error. Thicker lines (if present) indicate input uncertainty before addition of estimated additional uncertainty parameter",
label = 'crfs-cpfv-index-fit')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "index5_logcpuefit_Rec_PR.png"), 
caption = "Fit to log index data on log scale for recreational (CRFS) PR. Lines indicate 95% uncertainty interval around index values based on the model assumption of lognormal error. Thicker lines (if present) indicate input uncertainty before addition of estimated additional uncertainty parameter",
label = 'crfs-pr-index-fit')
```




```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "index5_logcpuefit_CCFRP.png"), 
caption = "Fit to log index data on log scale for CCFRP survey. Lines indicate 95% uncertainty interval around index values based on the model assumption of lognormal error. Thicker lines (if present) indicate input uncertainty before addition of estimated additional uncertainty parameter",
label = 'ccfrp-index-fit')
```



```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "index5_logcpuefit_CDFW_ROV.png"), 
caption = "Fit to log index data on log scale for CDFW ROV survey. Lines indicate 95% uncertainty interval around index values based on the model assumption of lognormal error. Thicker lines (if present) indicate input uncertainty before addition of estimated additional uncertainty parameter",
label = 'rov-index-fit')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "index9_standcpueall.png"), 
caption = "Standardized indices overlaid. Each index is rescaled to have mean observation = 1.0.",
label = 'standardized-indices')
```


<!-- ======================================================= -->  
<!-- ****************** Time Series ************************ --> 
<!-- ======================================================= -->


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "ts7_Spawning_output_with_95_asymptotic_intervals_intervals.png"), 
caption = "Estimated time series of spawning biomass",
label = 'ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "ts1_Total_biomass_(mt).png"), 
caption = "Estimated time series of total biomass",
label = 'tot-bio')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "ts9_Relative_spawning_output_intervals.png"), 
caption = "Estimated time series of fraction of unfished spawning biomass",
label = 'depl')
```


<!-- ====================================================================== -->
<!-- ******************    Reference Points    **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "SPR2_minusSPRseries.png"), 
caption = "Estimated 1 - relative spawning ratio (SPR) by year",
label = '1-spr')
```

\clearpage

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "SPR4_phase.png"), 
caption = "Phase plot of the relative biomass (also referred to as fraction unfished) versus the SPR ratio where each point represents the biomass ratio at the start of the year and the relative fishing intensity in that same year. Lines through the final point show the 95 percent intervals based on the asymptotic uncertainty for each dimension. The shaded ellipse is a 95 percent region which accounts for the estimated correlations between the biomass ratio and SPR ratio",
label = 'phase')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "yield2_yield_curve_with_refpoints.png"), 
caption = "Equilibrium yield curve for the base case model. Values are based on the 2022
fishery selectivities and with steepness fixed at 0.72",
label = 'yield')
```
