# Appendix F. CCFRP Index of Abundance {#ccfrp-index}



**California Collaborative Fisheries Research Program Index**

The California Collaborative Fisheries Research Program, [CCFRP](https://www.mlml.calstate.edu/ccfrp/), 
is a fishery-independent 
hook-and-line survey designed to monitor nearshore fish populations at a series of sampling 
locations both inside and adjacent to MPAs 
[@starr_variation_2015a; @wendt_collaborative_2009].  The CCFRP survey began in 
2007 along the central coast of California and was designed in collaboration 
with academics, NMFS scientists and fishermen. 
From 2007-2016 the CCFRP project was focused on the central California coast,
and has monitored four MPAs consistently. In 2017, the CCFRP expanded coastwide within California.  
The index of abundance was developed from the four MPAs sampled consistently 
(A&ntilde;o Nuevo and Point Lobos 
by Moss Landing Marine Labs; Point Buchon and Piedras Blancas by Cal Poly).

The survey design for CCFRP consists 500 x 500 m cells both within and 
adjacent to each MPA. On any given survey day site cells are randomly 
selected within a stratum (MPA and/or reference cells).  CPFVs are chartered 
for the survey and the fishing captain is allowed to search within the cell for 
a fishing location.  During a sampling event, each cell is fished for a total of 
30-45 minutes by volunteer anglers. Each fish encountered is recorded, measured, 
and can be linked back to a particular angler, and released (or descended to depth). 
 CCFRP samples shallower depths to avoid barotrauma-induced mortality.  
 Starting in 2017, a subset of fish have been retained to collect otoliths and fin 
clips that provide needed biological information for nearshore species. For the 
index of abundance, CPUE was modeled at the level of the drift, similar to the 
fishery-dependent onboard observer survey described above.


*CCFRP Index: Data Preparation, Filtering, and Sample Sizes*

The CCFRP data are quality controlled at the time they are key punched and little 
filtering was needed for the index. 
Cells not consistently sampled over time were excluded as well as cells that never 
encountered `r spp`.
The full dataset for northern California contained 8,770 drifts, 23% of which encountered 
`r spp`.  After applying filters to remove drfits from sites that were not consistently sampled,
marked for exclusion in the data, or did not fish a minimum of xxx, 7,078 drifts remained for 
for index standardization, with 1,757 drifts encountering `r spp`.
  

*CCFRP Index: Model Selection, Fits, and Diagnostics*

The CCFRP index includes all of the 
MPAs currently sampled from 2017-2020 and the core central California sampling sites 
from 2007-2016. Trends among all of the MPAs sampled increased along the entire coast 
from 2017-2020. The final index (Table \@ref(tab:tab-index-ccfrp)) 
represents a similar trend to the arithmetic mean of the annual CPUE (Figure \@ref(fig:fig-cpue-ccfrp)).

We modeled retained catch per angler hour (CPUE; number of fish per angler hour) 
using MLE fr. Indices with a year and area (location along the coast) interaction were not 
considered in model selection; trends in the average CPUE by region were similar 
in the filtered data set (Figure \@ref(fig:fig-areacpue-ccfrp)). Plots of the arithmetic 
mean by inside (MPA) and outside (REF) MPAs over time is in Figure \@ref(fig:fig-sitecpue-ccfrp) 
and shows the distinct trends of increasing average CPUE over time.


A negative binomial model was fit to the drift-level data (catch with a log offset for angler 
hours). Because the average observed CPUE inside MPAs and in the reference sites exhibited 
differing trends, we explored a YEAR:SITE interaction, which was selected as the best 
fit model by AIC Table \@ref(tab:tab-model-select-ccfrp)), The final model included
yrea, mpa/reference categorization, depth, depth squared, and a year:mpa/reference interaction. 
The model was fit using the sdmTMB R package (version xxx1). 


Based on work completed at the SWFSC, we estimate that the percent of rocky reef habitat from Point Conception to the California border within California state waters is 892 $km^2$, of which approximately 23% is in MPAs that prohibit the harvest of groundfish (pers comm. Rebecca Miller, UCSC). There is recreational fishing outside of state waters, but habitat maps are not available at the same 2-m resolution and do not allow for direct comparisons. To estimate the area 
of rocky substrate south of Point conception, we separted the southern California Bight into four areas, 1) CRFS District 
1 along the mainland coast, 2) CRFS District 2 along the mainland coast, 3) state waters encompassing the southern 
Channel Islands, and 4) state waters encompassing the northern Channel Islands.  We calculated the total area in each of the 
four regions, as well as the total area with available interpretted substrate.  By also calculating the total area open and closed to fishing, i.e., MPAs and CCAs, we expanded the known fraction of rocky substrate to the areas within state 
waters where no substrated interpretted maps exist.  This resulted in an estimate of 27% of the available rocky substrate 
within closed areas to fishing in southern California state waters. 

The final index was weighted, giving 20% of the model weight to MPAs and 80% of model 
weight to the "open" areas within the state.

