# Inforamtion Provided by the Commercial and Recreational Fleet Representatives


The copper rockfish STAT held the following three informal virtual meetings with stakeholders as part of the data exploration process:

\begin{enumerate}
\item Copper Rockfish & the Commercial Fisheries on January 10, 2023 (24 attendees)
\item Copper Rockfish  & the Recreational Fishery South of Pt. Conception on January 23, 2023 (17 attendees)
\item  & the Recreational Fishery North of Pt. Conception on January 30, 2023 (19 attendees)
\end{enumerate}


A summary of the information learned is provided here. We would like to thank everyone who participated in our virtual meetings and provided additional insight into the fisheries for copper rockfish and their perspective. 

## Preferred Habitat and Diet

Coppers are "king" of the reef and appear to push other species off of the best habitat within a reef.The STAT consistently heard from all fishermen that copper rockfish are not caught in areas of high relief. Copper rockfish prefer aras of flatter or broken hard bottom, and also venture out over soft bottom habitat. It is often larger fish caught over soft bottom where they are feeding on sanddabs. Copper rockfish do not feed on pyrosomes as frequently as other rockfish species.  When the pelagic red crabs are present, that is a preferred prey item. 






## Commercial Fishery

Copper rockfish are a component of the livefish fishery in both norhtern and southern California. They are intended to be sold live, but do not live will still be sold as dead fish. To fish copper rockfish commercial in California a deeper nearshore permit is needed.  The trip limits of 75 pounds per two month period for copper rockfish has impacted the commercial fleet. 
North of \CapeM the commercial fleet is restricted to shallower than 30 fm.

Many of the live fish buyers transport fish to Las Vegas Nevada or Los Angeles and San Jose in California. 
The market is constantly in flux. 

In southern California, a large portion of the live fish fishery collapsed during the COVID-19 pandemic and has not returned. A fisherman's market in San Diego has allowed individuals ot sell fish to the public.




Commercial fishermen from multiple areas along the coast emphasized that the price difference for copper by size is not as pronounced as it is for other species landed live.  North of San Francisco, the commercial fleet encounters larger copper rockfish (~ 7 pounds) in general.  Fish smaller than 2.5 - 3 pounds (approximately 14-17 inches) are desired by the live-fish buyers and the restaurant market and will sell for a higher price, and the lager fish can be sold to the general public.

South of Point Conception, copper rockfish are not generally a target species for the live fishery and have been difficult to market. The majority of commercial caught copper rockfish in southern California are sold dead.  The price of a dead copper in San Diego is around $8 a pound.

North of Point Conception, copper rockfish is a target of the 
North of Cape Mendocino (\CapeM), live fish sell for 3-4 times the price of dead copper. For fishermen targetting black rockfish in the north copper rockfish are incidental catch and still sold. 

Historically (pre RCAs) copper were found predominately in 45-80 fm. 

Out of Morro Bay, coppers ranging betwen 1-6 pounds are most common in teh 10-15 fm range and also sell for $7-8 a pound.

Coppers are encountered at an average depth of 45 fm, but can be found out to 60 fm. Copper are rately seen outside of 60 fm.

Copper rockfish are "king" of the reef 

Copper rockfish will follow prey targets, especially the pelagic red crabs that have been observed farther north.

Part of the U.S. fleet fishes in Mexican waters. THere are soem areas of higher copper rockfish density targeted in Mexican waters. 
Onotogentic shift and seasonal movements. Copper also tend to move based on weather conditions. North of \PtC, coppers cannot be found during bad weather and seem to move to deeper waters (swell and wind). 

Can keep copper live from depths up to 60 fms with no issue and seem to be the hardiest of the rockfish species. 
marketing them in southern california to a species as close to a "grouper" (bocaccio rockfish) and is working.

Commercial fishermen interested in tagging fish they release.

Fishing is more consistent in Mexican waters.

In central California (near Morro Bay) the nearshore live fish live in the kelp beds and larger coppers on the outside edges of the reef - you can find larger coppers on isolaed outcrops. It's rare for the commercial live fleet to fish outsdie fo 90 fee, and in central Cliafornia it's harder to ekepe them alive and those exihibing barotrauma will die in the tank, and the price of live fish much higher.



Issues raised
Would liek to see regional management. Sampling of the commercial live fleet is prohibitive due to the high price of copper and the low quota.  Descending more fish now with the lower quotas.
How will the stock assessment account for closed areas? They would like to see some accounting for these areas in the models.




## Recreational Fishery

### North of Point Conception
In 1997 there were 295 CPFVs in Califonria and in 2022 that number was 193 coastguard inspected active CPFVs that can carry 7 or more passengers. Of the 193 CPFVs in the state, 78 fish offshore exclusively.

During the COVID-19 pandemic, reduced loads were required on the CPFVs to maintain distancing among passengers.  Customers preferred the reduced loads that resulted in a less crowded vessel and have been willing to pay the increased charter costs to maintain the reduced loads post-COVID. 

The last 2-3 weeks of December, fishermen out of Emeryville, CA find aggregations of copper rockfihs that are not usually present on shale beds.

Coppers found over sandy bottom are feeding on sanddabs

Can find larger copper in 40-60 feet of water and swell is a good indicator for the presence of copper rockfish. If there's swell, the copper rockfish remain close to the bottm and are not as active, i.e., reduced chance of catching coppers.  In Eureka, copper are a desirable species in the recreational fleet due to the larger size. Coppers won't be caught more than 5-10 fm off the bottom. 

In central Califronia, small coppers can be found in 100+ feet of water at the edge of the Farallon Islands.

Copper are caught right on the bottom and are not eating pyrosome like some of the other species.  Small coppers have been caught off the the jetties in Humboldt, Pillar Point Harbor, and San Francisco, California



In Half Moon Bay, coppers are rarely observed shallower than 35 fathoms and they tend to only bite the bottom hook.
The gear regulations from unlimited hooks to 2 hoooks per line in 1999 resulted in increased loss of fish to sea lions. 

The majority of vessels north of Bodega Bay areVessels fishing out of Eureka generally fish closer to shore due to weather and fuel costs. The target in this area is salmon, and vessels will switch to rockfish espeically if salmon are not biting.

### South of Point Conception

There is less rocky habitat in southern California compared to northern California.

In southern California towards San Diego, coppers are typically found in less than 35 fathoms with juveniles in less than 10 fm.

At the Coronado Islands in Mexico, coppers are typically found in 28-35 fm on low relief habitat.

Southern california size classes of coppers are mixed and are not found in deeper waters, outside of 60 fm.

After the depth restrictions and other closures the fleet moved to different fishing ground and the desire for copper rockfish increased retention. 

Over half of the habiat regularly fished by the 1/2 vessels out of Misson Bay in San Diego is now in protected areas closed to fishing and the depth closures moved effort from offshore to inshore <50-60fm starting in 2001.

The effort of the fleet in southern California shifts during the summer months to pelagic species and kelp and sand bass, the timing of which is dependent on ocean temperatures. There is more pressure on the rockfish stocks during cold water years.

Around 2014/2014 as the economy recovered, business started increasing.

Captains change their targets for the day based on customer preference. 

The activity of private vessels is dependeing on ocean conditions, the vessel's size/range, and fuel costs.  Private vessels of >25 feet are usually focused on pelagic species and will fish rockfish during the transit to or from HMS grounds.  It's difficult for the private anglers to access offshore waters at depths of 50+ fm

In 2022, the CPFV fleet in southern California made a concerted effort to avoid copper rockfish grounds, and when copper rockfish were encountered, encouraged their clients to descend the fish. Anglers who were not catching as many fish were more interested in retaining their copper rockfish.

## Additional notes from the fishermen

Some of the webinar attendees participate in Cooperative Research, such as the NWFSC Hook-and-Line survey, the CCFRP and the SWFSC Cooperative Sampling Program.

During the NWFSC hook-and-line survey, the have been times when the vermilion and widow rockfish are abundant and the lines are reeled in before even reaching the bottom.  

Some of the fishermen in the recreational fleet are interested in deploying CTDs

In general rockfish catches decreased when prey (anchovis, mychtophics, and pyrosomes) are more abundance. 

Anglers who previously participated in ROV studies with NMFS observed rockfish species moving to the bottom and hiding in crevices when the ground swell reached 6-7 ft. There's interest in participation in future ROV surveys.