 
 ```{r, eval = TRUE}
Spp <- "Copper rockfish" 
spp <- "copper rockfish"
```
 
`r Spp` is a medium- to large-sized nearshore rockfish found from Mexico to Alaska.  The core range is comparatively large, from northern Baja Mexico to the Gulf of Alaska, as well as in Puget Sound.   `r Spp` have historically been a part of both commercial and recreational fisheries throughout its range. 

`r Spp` are commonly found in waters less than 130 meters in depth in nearshore kelp forests and rocky habitat [@love_milton_probably_1996]. The diets of `r spp` consist primarily of crustaceans, mollusks, and fish [@lea_biological_1999; @bizzarro_diet_2017-1]. The body coloring of `r spp` varies across the West Coast with northern fish often exhibiting dark brown to olive  with southern fish exhibiting yellow to olive-pink variations in color [@miller_guide_1972], which initially led to them being designated as two separate species (*S. caurinus* and *S. vexillaris*). 

Numerous genetic studies have been performed looking for genetic variation in `r spp`, with variable outcomes. Genetic work has revealed significant differences between Puget Sound and coastal stocks [@dick_replicate_2014]. Stocks along the West Coast have not been determined to be genetically distinct populations, but significant population subdivision has been detected, indicating limited oceanographic exchange among geographically proximate locations [@buonaccorsi_population_2002; @johansson_influence_2008]. A specific study examining `r spp` populations off the coast of Santa Barbara and Monterey California identified a genetic break between the north and south, with moderate differentiation [@sivasundar_life_2010]. 

`r Spp` are a relatively long-lived rockfish, estimated to live at least 50 years [@love_milton_probably_1996]. `r Spp` was determined to have the highest vulnerability (V = 2.27) of any West Coast groundfish stock evaluated in a productivity susceptibility analysis [@cope_approach_2011]. This analysis calculated species-specific vulnerability scores based on two dimensions: productivity characterized by the life history and susceptibility that characterized how the stock could be impacted by fisheries and other activities. 

