### Partnership for Interdisciplinary Studies of Coastal Oceans

The Partnership for Interdisciplinary Studies of Coastal Oceans [(PISCO)](https://www.piscoweb.org/) is an 
academic consortium conducting monitoring of coastal ecosystems in California as 
well as research to support marine protected area design.  Their work includes SCUBA 
surveys and fish recruitment monitoring within rocky reef habitats at a suite of sites 
across the state using standardized protocols so that multiple participating universities 
collect compatible data. 

The PISCO kelp forest fish survey data were downloaded from [DataONE](https://www.dataone.org/). 
We examined fish transect data collected by participating PISCO researchers at 
the University of California Santa Cruz (UCSC), University of California Santa Barbara 
(UCSB), the Vantuna Research Group (VRG) and Humboldt State University (HSU, now Cal Poly Humboldt) for potential 
development of a fishery-independent abundance index for use in the assessment model.  We 
ultimately concluded that the number of detections of `r spp` on transects was too low to 
be representative of relative abundance over time and the spatial distribution of sites
 having `r spp` were not well distributed across the coast.  Below we outline the structure 
of PISCO fish transect data, the procedure we used to filter to include `r spp` habitat,
and resulting sample sizes. Each fish transect location is surveyed by divers who count 
fish within a 30 x 2 x 2-m volume on the bottom, mid-way up the water column, and near 
the surface just below the kelp canopy.  Three replicate transects are performed within
inner, inner-mid, outer-mid, and deep zones of the reef corresponding to depths between 
5 and 20 m.  This results in 12 transect locations per reef site and 36 transect swims 
incorporating the three levels.  Divers count fish by species and estimate sizes.  Survey sites are typically grouped within a geographic area, i.e., there are three sites on Naples reef near Santa Barbara (Naples Central, Naples East, and Naples West).  

The full dataset was filtered for quality and habitat appropriate for `r spp`. 
Data was limited to surveys conducted by UCSC and UCSB because `r spp` were not 
observed by HSU and sites surveyed by VRG typically either saw very few `r spp` 
or were not consistently sampled across the time series.  The UCSC and UCSB campus 
sites were separated to develop two indices for the northern and southern models.
We eliminated sites that were sampled in less than 80 percent of the survey years for each campus.  `r Spp` were only observed on bottom transects and so mid-water and canopy transects were removed.  The inner reef (shallow) transects were removed due to rare `r spp` observations.  Divers noted approximate water visibility and transects with visibility less than 3 m were removed.  We also retained only fish greater than 17 cm to construct an adult index.  

```{asis, echo = model.area=='north'}

Early years with less consistent sampling were eliminated such that the time series for UCSC began in 2001 and extended through 2021.  The majority of UCSC sites occurred within sites that became MPAs.  Three sites that did not become MPAs were removed to create an index with a consistent change in selectivity following MPA implementation.  After filtering, sites that remained in the UCSC dataset were centered around the Monterey peninsula. Sample sizes of copper rockfish observed by year at all retained UCSC sites ranged from 1 to 28 fish (Table \ref{tab:pisco-data}).

```

```{asis, echo = model.area=='south'}

Early years with less consistent sampling were eliminated such that the time series for UCSB began in 2004 and extended through 2021.  Sites surveyed by UCSB were mixed in distribution inside and outside MPA locations and therefore were not filtered for this criterion.  After filtering, sites that remained in the UCSC dataset were centered around the northern Channel Islands with a few on the Santa Barbara Channel mainland. Sample sizes of copper rockfish observed by year at all retained sites ranged from 15 to 39 fish for UCSB (Table \ref{tab:pisco-data}).  

```

The PISCO program also conducts larval fish recruitment monitoring by sampling 
artificial settlement substrates called Standard Monitoring Units for Recruitment
of Fishes (SMURFs).  Similar to the SCUBA surveys, SMURF surveys are conducted by 
multiple universities using standardized protocols.  We examined data collected by 
the UCSB and UCSC campuses in southern and central California.  Surveys by UCSB were 
conducted between 2000 and 2018 and by UCSC between 1999 and 2016.  Juvenile `r spp` 
are difficult to distinguish from juvenile gopher rockfish (*Sebastes carnatus*) and the 
data from UCSB combines counts of these species into a complex.  For this reason, 
we determined this data to be inappropriate for construction of a `r spp` recruitment 
index to be used within the assessment.  While data from UCSC reports distinct counts 
of copper and gopher rockfish, the concern remains that the `r spp` counts may not be 
accurate due to this morphological identification difficulty.  Additionally, collections 
of `r spp` in this data set were very sparse with many years seeing none.  However, 
an extremely high number were recorded for 2016.  

### Reef Check

[Reef Check](https://www.reefcheck.org/) is an international non-profit organization utilizing citizen scientists 
to monitor reef habitats.  Data from SCUBA surveys of fish in California are available 
since 2006.  Given the low proportion of `r spp` detections on PISCO surveys, we did not 
dedicate time to analysis of Reef Check survey data for the purpose of abundance index development.  

### Visual Surveys

The SWFSC and UCSB both conduct visual surveys using ROVs and submersible vehicles. We used the observations of copper rockfish from these data to inform our understanding of the species' distribution. We also used these data as a visualization of data gaps that can inform future research. The visual surveys ranged from 1993 to 2018 from Monterey south to the California/Mexico border.A total of 3,976 individual `r spp` were observed at average transect depths ranging from 20 to 156 m, with an average of 67 m.  The depth ranges of these surveys, especially dives from the 2007 submersible survey of the Southern California Bight extended into much deeper waters to cover the depth range of cowcod (@yoklavich_fisheryindependent_2007). The UCSB submersible survey sampled the natural reefs and the oil platforms southern California from 1995-2011 and could be explored as an index of abundance for copper rockfish in the future @love_potential_2006.

### MRFSS Dockside Survey of CPFV/PC Vessels

```{r, echo=FALSE, results='asis'}
filein = file.path(doc_dir, "shared_text",'21f_mrfss_index.Rmd')
read_child(filein)
```

```{asis, echo = model.area=='south'}

The data were filtered to identify rockfish trips, standardized across the time series, and modeled to estimate and index of abundance for `r spp`. The MRFSS CPFV index of abundance between 1980-1999 is generally variable but with a flat trend in abundance except for three years that spike in abundance estimates (Figure \ref{fig:mrfss-cpfv-index-fit}). These same patterns in sharp increases in the index for select years were also observed in the raw data. Given the limited information in the data to understand what was behind these unexpected spikes in the time series, the MRFSS index of abundance was not used in the final base model. 
```


```{asis, echo = model.area=='north'}

The data were filtered to identify rockfish trips, standardized across the time series, and modeled to estimate and index of abundance for `r spp`. The MRFSS CPFV index of abundance between 1980-1999 is quite variable with notable periods of an increasing trend followed by a decline and then another increasing tren (e.g., increasing between 1982-1984, drop in 1985, and increasing between 1985-1987, Figure \ref{fig:mrfss-cpfv-index-fit}). These same patterns in increases and decreases in the index for select years were also observed in the raw data. Given the limited information in the data to understand what was behind these unexpected spikes in the time series, the MRFSS index of abundance was not used in the final base model. 
```
