# Appendix H. CPFV Fleet Description, Sampling, and Trip Types  {#cpfv-samples}

The CDFW conducts several surveys are part of the CRFS program, including an onboard observer survey, angler interviews, and a required CPFV logbook for each trip. The [CRFS sampling manual](https://nrm.dfg.ca.gov/FileHandler.ashx?DocumentID=62348&inline) outlines the sampling methodologies for each survey component.  The state of California allows the filleting of fish at sea; to accurately identify rockfish to species and obtain measurements of whole fish the majority of angler interviews occur onboard the vessel for the CPFV fleet. 

The [California Fisheries Recreational FIsheries Survey Methods](https://nrm.dfg.ca.gov/FileHandler.ashx?DocumentID=36136&inline) indicates the CPFV "sampling goal is to sample onboard at the historical sampling frequency of two to five percent of estimated CPFV trips of interest (e.g., trips targeting groundfish, inshore and coastal pelagic species) at each CPFV landing and to sample other CPFV trip types dockside."  The CPFV fleet is not required to speciate the catch in the logbooks.

The CPFV fleet north and south of Point Conception are fundamentally different in terms of the vessels fishing, available target species, and also fishery regulations over the past twenty years. The CPFVs north of Point Conception targeting groundfish to not typically target other species on the same trip, with the exception being a half day bottomfish trip mixed with a half day of Dungeness crab pot fishing. The fleet north of Fort Bodega Bay, California is dominated by smaller 6-pack vessels with limited capacity.  It may not be possible for a sampler to ride onboard a 6-pack vessel if it's at capacity. There are no overnight trips in California.

In southern California, the diveristy of targt species is higher an includes several bass species, state managed gamefish, coastal pelagics, and highly migratory species, as well as boats that fish in Mexican waters. The trip types in southern California include 1/2 trips where vessel will run two trips a day, 3/4 day trips to fishing grounds further offshore, such as the Channel Islands, and overnight boats that can access areas like San Nicholas in the southern Channel Island or may be combination trips fishing for tunas, but also catching rockfish limits. The diversity of trip types and mixed target trips in southern California pose a challenge for both sampling and managing the fisheries.

The tables below represent the sum of trips from 2018 and 2019 combined as they are the two years pre-COVID that best represent the CPFV fleet's activity.  We filtered the CPFV logbook data to trips that recorded at least one rockfish and the CPFV onboard observer data to trips that encountered at least 5% rockfish species. We aggregated within each dataset across 2018 and 2019 and areas where necessary to ensure confidentiality requirements were met. The combined sampling rate from 2018-2019 was three percent of all CPFV trips in the data used. There were no observed trips in CRFS district 5 in 2018-2019 where 1,052 CPFV logbook records that recorded at least one rockfish.  

There were 60 trips recorded as multi-day trips in northern California. This represented less then 1% of the trips in northern California and we did not investigate the accuracy of these entries. In southern California, 14% of CPFV logbook trips were recorded as multi-day trips and 1% of the CRFS onboard observer trips were from multi-day trips.  

When weather allows, the northern Channel Islands can be accessed from CRFS district 2 during a 3/4-1 day trip or a multi-day trip, depending on the port. For instance, the CPFVs from Oxnard, California access the northern Channel Island during multi-day trips, and the same areas are accessed by the 3/4-1 day boats out of Santa Barbara Landing. 


In CRFS District 1, 79% of the onboard observer trips were from 1/2 day trips, whereas in District 2 this represented 29% of the observed trips.  The vessels in District 2 typically offer fewer 1/2 day trips and fish the nearshore when weather precludes a trip to the northern Channel Islands. 

Approximately 6% of the logbooks from District 1 recorded a block number in Mexican waters as the primary location fished. Fewer than 10 trips that recorded block numbers along the mainland of southern California were recorded a multi-day trips.  These were assumed to be single-day trips and added to the single day category.  

One block number is recorded per CPFV logbook.  In southern California, 70% of the trips fishing the northern Channel Island and 57% of the trips fishing the southern Channel Islands were recorded as single day trips. 




Add tables of cpfv logbook by block (or district) and year
Add table of the number of onboard trips by year
Add the number of trips fishin in the cdfw blocks 


