### Northwest Fisheries Science Center Hook and Line

#### Index of Abundance 
\

Since 2004, the NWFSC has conducted an annual hook and line survey targeting shelf rockfish in the genus *Sebastes* at fixed stations (e.g., sites, Figure \ref{fig:nwfsc-hkl-map}) in the Southern California Bight. Key species of rockfish targeted by the `r hkl` are bocaccio (*S. paucispinis*), cowcod (*S. levis*), greenspotted (*S. chlorostictus*), and vermilion/sunset (*S. miniatus* and *S. crocotulus*) rockfishes, although a wide range of rockfish species have been observed by this survey. During each site visit, three deckhands simultaneously deploy 5-hook sampling rigs (this is referred to as a single drop) for a maximum of 5 minutes per line, but individual lines may be retrieved sooner at the angler's discretion (e.g., to avoid losing fish). Five drops are attempted at each site for a maximum possible catch of 75 fish per site per year (3 anglers fishing with a line with 5 hooks across a total of 5 drops per site). Further details regarding the sample frame, site selection, and survey methodology are described by Harms et al. [-@harms_noaa_2008]. 

From 2004 through 2013, sampling was conducted only outside the Cowcod Conservation Areas (CCAs). Beginning in 2014, 40 sites inside the CCAs were sampled, and roughly another 40 sites have been added in subsequent years inside the CCAs. It is important to note that some portions of the CCAs allow take for select species at depths less that 73 meters. The survey currently has 201 sites (79 inside and 122 outside the CCAs). Additionally, 16 stations within the original sample design have been converted into either state or federal MPAs between 2007 - 2011 and continue to be sampled annually.  

While `r spp` have not been encountered in large numbers similar to some of the other commonly encountered species (vermilion/sunset, bocaccio, greenspotted rockfish) in the `r hkl`, `r spp` has been observed every year that the survey has been conducted (Table \ref{tab:nwfsc-hkl-pos-year}). Observations of `r spp` commonly occur across a range of depths between 30 - 120 m with observations peaking around 80 m (Table \ref{tab:nwfsc-hkl-pos-depth} and Figure \ref{fig:nwfsc-hkl-depth}). Across all sample years and sample sites the `r hkl`  has observed a total of 1,213 `r spp`. While `r spp` have been observed both outside and inside the CCAs in areas that restrict take or MPAs (Figures \ref{fig:nwfsc-hkl-site}), the vast majority of observations of `r spp` have been outside the CCAs (1,060 observations, Tables \ref{tab:nwfsc-hkl-obs}). The number of `r spp` observations within the no take areas of the CCAs or MPA and open areas was explored to determine if the catch rates of `r spp` differed among the areas which determined there was not a substantial difference in the observations among these areas (Table  and \ref{tab:nwfsc-hkl-obs-mpa}). Additionally, the data from the `r hkl` was broken out into three regions: mainland, Northern Channel Islands, and Southern Channel Islands. The highest catch rate of `r spp` was observed around the Northern Channel Islands (Figure \ref{fig:nwfsc-hkl-region-main}). 

The STAT explored alternative model structures to generate a standardized index of relative abundance. The final model selected was a model with a delta-lognormal error structure with factors of year, region, drop, covariates of number of vermilion and bocaccio observed, year/region interaction, and with random site effects. Finally, the index was weighted by the estimated proportion of rocky habitat by region. A single index of abundance was calculated using all observations from this survey (Figure \ref{fig:nwfsc-hkl-index-main}). Details regarding the index of abundance, sample sizes and model selection can be found in the Appendix Section \ref{nwfsc-hkl-model}. 

The composition and index of abundance data from the `r hkl` have been included in other nearshore assessments using various approaches. For species where the expansion of the survey into the CCAs was expected to impact the size of fish observed by this survey (e.g., vermilion/sunset rockfish and cowcod), one approach has been to estimate a single index of abundance for the whole time series but to only associate composition data collected by the survey (lengths and ages) from 2014  onward to estimate a single selectivity curve representative of the expansion of the survey, with composition data collected prior to 2014 being added to a separate fleet in the model. Since the initial analysis of the data did not indicate large changes in the catch rates or size of fish observed pre- and post-survey expansion for `r spp` all composition data were used within the base model but a sensitivity that used this approach was conducted (see the [Sensitivities Section](#sensitivities) below). 

#### Composition Data 
\

`r Spp` caught in the `r hkl` were generally between 30 and 50 cm for both sexes (Figures \ref{fig:nwfsc-hkl-site-len} and \ref{fig:hkl-len-data}). The number of lengths and ages collected by the survey are shown in Table \ref{tab:nwfsc-hkl-samples} and the length-at-age by sex is shown in Figure \ref{fig:nwfsc-hkl-len-age}. The mean length observed by year was variable with an appreciable drop in the mean size observed in 2012 but has gradually increased in the subsequent years (Figure \ref{fig:mean-hkl-len-data}). 

