### Growth Data {#growth-data}

A significant amount of additional length-at-age not associated with fishery fleets or surveys incorporated in the model were available for `r spp`. These age data collection efforts from three programs `r area` since 2004: 621 otoliths collected by the NWFSC WCGBT survey, 33 otoliths collected by a research survey conducted by Don Pearson, and 506 otoliths collected by a cooperative research survey by the SWFSC and CPFV funded by the Sportfishing Association of California (Table \ref{tab:growth-age-samps}). Numerous explorations were conducted to evaluate how best to incorporate these data within the base model were conducted. These data were split into two growth fleets based on the collection method. The samples from the `r wcgbt` were split into their own growth fleet and the lengths associated with the ages were added to the model to estimate a length-base selectivity for these samples collected via trawl gear (Figures \ref{fig:growth-wcgbt-len} and \ref{fig:growth-mean-wcgbt-len}). The ages collected by Pearson and the CPFV cooperative research samples were combined into a second growth fleet. The Pearson Research ages were combined with the CPFV cooperative collection ages since the majority of Pearson Research ages were in CDFW district 2 similar to the CPFV collected ages. The length associated with these fish were included in the model to estimate a length-based selectivity (Figures \ref{fig:growth-coop-len} and \ref{fig:growth-mean-coop-len}). These collection had a wide distribution of length and ages observed (Figures \ref{fig:growth-len-dist} and \ref{fig:growth-age-dist}).
