### Northwest Fisheries Science Center West Coast Groundfish Bottom Trawl Survey

The Northwest Fisheries Science Center (NWFSC) West Coast Groundfish Bottom Trawl (WCGBT) survey is based on a random-grid design; covering the coastal waters from a depth of 55-1,280 m [@bradburn_2003_2011]. This design generally uses four industry-chartered vessels per year assigned to a roughly equal number of randomly selected grid cells and divided into two 'passes' of the coast. Two vessels fish from north to south during each pass between late May to early October. This design therefore incorporates both vessel-to-vessel differences in catchability, as well as variance associated with selecting a relatively small number (approximately 700) of possible cells from a very large set of possible cells spread from the Mexican to the Canadian borders.

The observations of `r spp` by the `r wcgbt` are limited. The `r wcgbt` uses trawl gear to sample sandy bottom areas off the West Coast and _a priori_ it would not be expected to be an informative data source for `r spp`, which are generally more closely associated with rock substrate. The `r wcgbt` had limited positive tows by year where `r spp` were observed within this area, preventing the calculation of an index of abundance for `r spp` (Table \ref{tab:wcgbt-pos-tows}). The catch-per-unit-effort across all years for the NWFSC WCGBT survey is generally small, excluding one single tow from 2012 where 1.9 mt of `r spp` were caught (Figure \ref{fig:wcgbt-cpue}). The observations of `r spp` by the NWFSC WCGBT survey commonly occur between 50 - 120 meters (Figure \ref{fig:wcgbt-depth}). However, the `r wcgbt` has regularly collected length and age samples from positive tows for `r spp` (Figure \ref{fig:wcgbt-len-age}). These data were used as conditional-age-at-length data to inform the estimation of growth within the model (Table \ref{tab:growth-age-samps}).  

