## Additional Considered Data Sources


```{r, echo=FALSE, results='asis'}
filein = file.path(doc_dir, "shared_text",'21_surveys_not_included.Rmd')
read_child(filein)
```


### Northwest Fisheries Science Center West Coast Groundfish Bottom Trawl Survey

The NWFSC West Coast Groundfish Bottom Trawl (WCGBT) survey is based on a random-grid design; covering the coastal waters from a depth of 55-1,280 m [@bradburn_2003_2011]. This design generally uses four industry-chartered vessels per year assigned to a roughly equal number of randomly selected grid cells and divided into two 'passes' of the coast. Two vessels fish from north to south during each pass between late May to early October. This design therefore incorporates both vessel-to-vessel differences in catchability, as well as variance associated with selecting a relatively small number (approximately 700) of possible cells from a very large set of possible cells spread from the Mexican to the Canadian borders.

The observations of `r spp` by the `r wcgbt` are limited. The `r wcgbt` uses trawl gear to sample sandy bottom areas off the West Coast and _a priori_ it would not be expected to be an informative data source for `r spp`, which are generally more closely associated with rock substrate. The `r wcgbt` had limited positive tows by year that observed `r spp` within this area, preventing the calculation of an index of abundance for `r spp` (Table \ref{tab:wcgbt-pos-tows}). The catch-per-unit-effort across all years for the NWFSC WCGBT survey is generally small, excluding one single tow from 2012 where 1.9 mt of `r spp` were caught (Figure \ref{fig:wcgbt-cpue}). The observations of `r spp` by the NWFSC WCGBT survey commonly occur between 50 - 120 meters (Figure \ref{fig:wcgbt-depth}). The `r wcgbt` has regularly collected length and age samples from positive tows for `r spp` `r area` (Figure \ref{fig:wcgbt-len-age}). These data were used as conditional-age-at-length data to inform the estimation of growth within the model. See the [Length-at-Age](#length-at-age) section for data used to inform growth estimation.


### California Cooperative Oceanic Fisheries Investigations

The California Cooperative Oceanic Fisheries Investigations (CalCOFI) survey began in 1951 and conducts quarterly cruises off southern and central California, collecting a suite of hydrographic and biological data at fixed stations and while underway; ichthyoplankon sampling with a paired bongo started in 1978. Data on larval abundance from the CalCOFI Ichthyoplankton survey have been used in stock assessments of several species, including bocaccio, cowcod and shortbelly rockfish. Although the long-term dataset is limited to a subset of species for which morphological identification of larvae has been possible, recent research has been successful at identifying a broader range of species based on genetic
identification of larvae [@thompson_rockfish_2016]. Larval fish were enumerated from winter samples from 1998 to 2013.  Out of 36 sites, 12 observed a larval `r spp` at least once, predominantly around the northern Channel Islands.  After selecting for only those sites that observed `r spp`, we examined the proportion of positive net tows by year and the average number of `r spp` observed per tow.  Given that these values were low and the sites observing `r spp` were not well distributed, we did not use these data to develop a spawning output index for use in the assessment. 

### Southern California Bight Publicly Owned Treatment Works

In the Southern California Bight, a number of monitoring programs exist to evaluate the potential consequences of effluent discharges from waste water treatment facilities on the coastal marine environment. As over 20 million people live within an hour’s drive of the ocean in this region, a major impact to this ecosystem includes a cumulative total of 1.5 billion
liters of treated effluent released each day to the ocean, originating from 17 major waste water treatment plants. Most of these publicly owned treatment works support monitoring programs to evaluate the impacts on water and sediment quality, and associated ecological communities. For several, this includes bottom trawl surveys of coastal habitats, representing some of the longest running trawl surveys available in the region. Despite being limited spatially to waters close to population centers, these data have previously been used in stock assessments of cowcod (_Sebastes levis_) [@dick_status_2019] and California scorpionfish (_Scorpaena guttata_) [@monk_status_2017]. Investigations indicated the `r spp` are rarely observed in this survey and did not support the development of an index for this assessment.
