### California Department of Fish and Wildlife Remotely Operated Vehicle Survey

#### Index of Abundance
\

```{r, echo=FALSE, results='asis'}
filein = file.path(doc_dir, "shared_text",'10_appendix_rov.Rmd')
read_child(filein)
```

The number of transects by year, location, site designation, and the numbers of `r spp` observed are shown in Table \ref{tab:rov-obs}. South of Point Conception the CDFW ROV survey generally saw the largest numbers of `r spp` around the Northern Channel Islands similar to the `r hkl` (Figure \ref{fig:rov-obs-loc}). The trend in the calculated catch-per-unit-effort based on the data alone was highly variable across sampling locations and by MPA or Reference area (Figure \ref{fig:rov-raw-cpue}).   

CDFW provided an initial analysis of the CDFW ROV survey data which helped in determination of which modeling approaches would be considered for these data. The STAT explored a range of alternative model structures to generate a standardized index of relative abundance for this survey. The final model selected was a delta-gamma hurdle model where the numbers of fish observed were predicted by year, site designation (MPA or Reference), proportion soft terrain, year/site designation interaction, and a random effect for the year/location interaction.  Details regarding the index of abundance, sample sizes and model selection can be found in the Appendix Section \ref{cdfw-rov-index}.

#### Composition Data 
\

Length measurements were made from images taken with stereo-cameras by the CDFW ROV survey in 2014, 2015, 2019, 2020, and 2021. The ROV was equipped with two locally recorded stereo cameras mounted in a fixed orientation in parallel with the primary forward-facing camera used for navigation, identification and enumeration. Paired stereo video cameras were calibrated to provide accurate feature measurements by MARE prior to in-field data collection. Fish length was determined based on a photogrammetric intersection to calculate 3D coordinates from measured image coordinates to measure fork length to the nearest millimeter. Processors selected two 3D points, fish head and tail, on both time-synced port and starboard stereo images. Processors made note of a generated precision value that was computed alongside each measurement. The software then computed the Euclidean distance between the two 3D points to give a length measurement. Sizes were rounded to the nearest centimeter. The precision of estimates was determined and represents the repeatability and geometric quality of a measurement, and is dependent upon the location of the individual in the camera view and the clarity of the point measured. Precision values greater than 10 mm were recorded in the database alongside measurements, as precision values less than 10 mm meant measurements were deemed fully repeatable. Fish observations from initial species scoring were marked “not sizable” if the nose/tail of the fish was cut off in either stereo view, the fish was missing in one view, or the orientation of the fish obscured measurement or produced an extreme precision measurement. Fish were marked “not visible” if the fish was not visible in either the port or starboard image. Fish marked “not sizable” and “not visible” were removed from the final data set submitted by CDFW. 

The sizes observed by MPA and Reference areas north and south of Point Conception varied with a higher density of smaller fish being observed in the Reference areas (Figure \ref{fig:rov-len}). The length data by designation, MPA and Reference, were weighted based on the estimated rocky habitat within each designation north and south of Point Conception (73 and 80 percent of areas open to fishing in the north and south, respectively,  see Appendix Section \ref{cdfw-rov-index} for additional information). The CDFW ROV survey observed `r spp` between 15-50 cm in length with lower mean lengths observed in 2014 and 2015 compared to the later period between 2019-2021 (Figures \ref{fig:rov-len-data} and \ref{fig:mean-rov-len-data}).