## Base Model Results

The base model described here is only for the portion of the stock `r spp` in California.  Descriptions of the summed total biomass, spawning output, and stock status for the California stock of `r spp` are described in later sections.  

The base model parameter estimates along with approximate asymptotic standard errors (SD column) are shown in Table \ref{tab:params} and the likelihood components are shown in Table \ref{tab:south-likes}. The estimated data weights by the Francis method are shown in Table \ref{tab:dw}. Estimates of derived reference points and approximate 95 percent asymptotic confidence intervals for only the population `r area` are shown in Table \ref{tab:south-reference}. Estimates of the `r spp` population size `r area` over time are shown in Table \ref{tab:south-timeseries}. 

### Parameter Estimates

The estimates of growth parameters by sex varied relative to the externally estimated starting values.  The length-at-age 2 and the length-at-age 20 estimates for both sexes was slightly less than the external estimates but were well within the 95 percent confidence interval given the estimated uncertainty (Table \ref{tab:params} and Figure \ref{fig:mod-est-len-age}). The estimated $k$ for female were greater than the values estimated externally using the survey age data while the male value was similar to the external estimate (`r round(model$parameters[model$parameters$Label == "VonBert_K_Fem_GP_1", 3],3)` yr^-1^ for females and `r round(model$parameters[model$parameters$Label == "VonBert_K_Mal_GP_1", 3],3)` yr^-1^ for males).  The majority of female and male `r spp` growth occurs at younger ages, reaching near maximum length by age 10-15, with female `r spp` reaching marginally larger maximum lengths (Figure \ref{fig:mod-est-len-age}). 

Length-based selectivity curves were estimated for the fishery and survey fleets. The majority of fishery and survey fleets were parameterizing using the double normal selectivity parameterization in SS3 except for the commercial dead and `r hkl` fleets that were parameterized as logistic asymptotic selectivity. The estimated selectivities are shown in Figure \ref{fig:est-selex}. The selectivity for commercial dead fleet was estimated to be asymptotic and constant across the model period. The commercial live fish fishery selects fish at small sizes with dome-shaped selectivity. Both recreational fleets were estimated dome-shaped selectivity for each selectivity period with the CPFV fleet selecting a higher portion of large fish in the final time block relative to the PR fleet. The peak in selectivity for both the CPFV and PR fleets in the final time block were estimated at `r round(model$estimated_non_dev_parameters[rownames(model$estimated_non_dev_parameters) == "Size_DblN_peak_Rec_CPFV(3)", "Value"], 1)` and `r round(model$estimated_non_dev_parameters[rownames(model$estimated_non_dev_parameters) == "Size_DblN_peak_Rec_Private(4)", "Value"], 1)`, respectively.  While the recreational fleets select a wide range of sizes, the estimated peak of selectivity for both fleets were notably less than the size-at-50 percent maturity of 33.7 cm.

The CCFRP Hook and Line and CDFW ROV surveys estimated peak selectivity around 40 cm with selectivity decreasing for larger fish. The `r hkl` estimated asymptotic selectivity only reaching maximum selectivity for the largest fish. The `r wcgbt` which samples soft bottom via trawl gear had relatively low selectivity for the majority of sizes with only selectivity peaking at the largest sizes. Finally, the estimated length-based selectivity from the CPFV cooperative collection and Pearson Research study was asymptotic with full selectivity for fish of 35 cm and larger.  Both of these last two fleets included only lengths and ages to inform growth estimation. As noted in the Growth Data Section \ref{growth-data} that describes these data, the estimated selectivity for the samples collected by the CPFV vessels participating in the cooperative sampling program was distinctly different than that from the CPFV fleet operating `r area` as a whole. This is likely due to the areas accessible and trip type (half-day, three-quarter day, or overnight) between the CRFS districts 1 and 2 within this area where all vessels participating in the collaborative collections operating out of district 2.

The catchability for each of the surveys was analytically solved comparing observed to expected vulnerable biomass across all years. The analytical values for catchability were very small given the survey methodologies and are reported in Table \ref{tab:params} in log-space.  Additional fishery and survey index variability, process error added directly to each year's input standard deviation for the were estimated within the model. The model estimated the largest added variance of `r round(model$parameters[model$parameters$Label == "Q_extraSD_Rec_Private(4)", 3], 3)` for the recreational PR fishery index. In contrast the model estimated only limited additional variability in order to fit the recreational CRFS CPFV fishery index (`r round(model$parameters[model$parameters$Label == "Q_extraSD_CRFS_CPFV(8)", 3], 3)`). The model fit the trends in the `r hkl` index of abundance relatively well with only a small amount of added variance  being estimated to fit this time series (`r round(model$parameters[model$parameters$Label == "Q_extraSD_NWFSC_HKL(7)", 3], 3)`). The model estimated an added variance of `r round(model$parameters[model$parameters$Label == "Q_extraSD_CCFRP(5)", 3], 3)` and `r round(model$parameters[model$parameters$Label == "Q_extraSD_CDFW_ROV(6)", 3], 3)` to the indices from the CCFRP and CDFW ROV surveys, respectively.

The time series of estimated recruitments and annual recruitment deviations are shown in Figures \ref{fig:recruits} and \ref{fig:rec-devs}. Years with the highest recruitment deviations were estimated to have occurred in 2010 and 2013 with the lowest being estimated in 2018 and 2019. There is limited information regarding recruitment prior to 1980 but are estimated in the base model to account for uncertainty around the unfished condition. The historical age age data from the CPFV fleet from 1975 were identified to have a disproportional influence on estimated recruitment in the late 1960s relative to all other data sources in the model. These data resulted in a sharp spike in recruitment during these years that was substantially higher than any other year in the model.  Given that these estimates were extreme and appeared to be informed by limited data, the decision was made to reduce the influence of this one year of limited age data for model stability (lambda value of 0.10 for these data). Sensitivities showed that the overall ending model estimates were not impacted by this decision (show below in Sensitivities Section \ref{sensitivities}). Estimated recruitment deviations during the early years when compositional data began, 1975 - 1995, have relatively high uncertainty intervals indicating lack of support for clear strong or poor recruitment years across data sources. Recruitment deviations after 2017 are relatively uncertain but with large negative recruitment deviations. Recruitment is estimated based on the spawner-recruit curve in 2021 and 2022  (Figure \ref{fig:bh-curve}). The recruitment bias adjustment applied within the model across years is shown in Figure \ref{fig:bias-adjust}.


### Fits to the Data

Fits to the length data are shown based on the Pearson residuals-at-length, the annual mean lengths, and aggregated length composition data for the fishery and survey fleets in the model. Annual length composition fits are shown in the Appendix, Section \ref{length-data}.  

The aggregated fit to the length composition data by fleet is shown in Figure \ref{fig:len-agg-fit}. The majority of the length composition from the commercial dead fleet were unsexed fish with sexed fish only occurring for select years for limited samples (1986, 1987, and 2022). On aggregate the model fit the unsexed length composition generally well with the single asymptotic selectivity curve. Pearson residuals for the commercial dead fishery length data are shown in Figure \ref{fig:com-dead-pearson}. The data across time are limited making it difficult to discern patterns in the Pearson residuals across time particularly since the data were not sufficient to support the estimation in varying selectivity across time which would be expected given changes in management. The mean length observed by year from the commercial fleet were uncertain but with a relatively stable mean size in the final years of the model but with a larger mean size observed in the available data prior to 1990 (Figure \ref{fig:com-dead-mean-len-fit}). There were only limited ages available from the commercial dead fleet in 2022 with a rather large Pearson residuals (Figures \ref{fig:agg-marg-age-fit} and \ref{fig:com-dead-age-pearson}), noting that there were only 8 ages available that happened to all be female. The Pearson residuals for the commercial live fish fishery did not appear to have patterns or periods of misfit to th data (Figure \ref{fig:com-live-pearson}) and the model appeared to fit the mean size across time which was highly variable (Figure \ref{fig:com-live-mean-len-fit}). 

The length composition data aggregated across years from the CPFV fleet was fit well by model (Figure \ref{fig:len-agg-fit}). The Pearson residuals for the recreational CPFV length data are variable by year (Figure \ref{fig:rec-cpfv-pearson}). Pearson residuals were positive, observations greater than expected, for larger fish in the earliest data. Additionally, there appears to be a series of diagonal positive residuals moving across years starting around 2005 which may be a year-class moving through the population that the model is under-estimating. These under fits to the data could align with the positive recruitment deviation being estimated in 2003 for the population. Explorations of alternative selectivity forms failed to resolve this pattern in residuals. The mean length observed by the CPFV fleet was fit relatively well by the model with the largest mean size being observed in the early years of the data with the mean size roughly stabilizing between the late 1980s though 2010, after which there was a mean decline in the mean size and then slowly increasing at the end of the model period (Figure \ref{fig:rec-cpfv-mean-len-fit). Age data were available for the CPFV fleet only in 1975 with all ages being unsexed fish (Figure \ref{fig:agg-marg-age-fit}). The peak of the distribution of these ages was under-fit by the model (Figure \ref{fig:rec-cpfv-age-pearson}). These ages where highly influential in model leading to a large recruitment deviation that was significantly higher than any other year estimated. All data weighting approaches explored wanted to significantly up-weight these data (e.g., suggested weights of greater than 1.0 where the input sample size was equal to the number of fish). Due to the highly influential nature of this single year of data these data were down-weighted in the model. Model explorations showed that down-weighting of these data did not effect the ending model estimates but resulted in a more stable model.

The aggregate length composition data from the PR fleet had a slightly higher peak around 30 cm with fewer observations of larger fish relative to the CPFV fleet and was fit well by the model (Figure \ref{fig:len-agg-fit}). The Pearson residuals for the recreational PR length data are variable by year (Figure \ref{fig:rec-pr-pearson}). Similar to the CPFV length data, there appears to be a series of diagonal positive residuals moving across years starting around 2005 which may be a year-class moving through the population that the model is under-estimating that were not able to be resolved.  The mean length observed by the PR fleet was highly variable prior to 2001 with the model estimated mean length being either below or above the observed mean length (Figure \ref{fig:rec-pr-mean-len-fit}). After 2001, the variability around the mean length decreases with the model roughly able to fit the decrease in mean length after 2010 and the recent increases in mean length (Figure \ref{fig:rec-pr-mean-len-fit}). 

The CCFRP Hook and Line survey aggregated lengths had a sharp peak between 30-40 cm that the model underestimated but fit the ascending and descending length observed well (Figure \ref{fig:len-agg-fit}). The was no clear pattern in the Pearson residuals for this data source (Figure \ref{fig:ccfrp-len-pearson}). The model estimated mean length was increasing between 2017-2021, while the CCFRP data had a declining trend in mean length observed for this period (Figure \ref{fig:ccfrp-mean-len-fit}). However, the estimated model fit was well within the variance in the observed lengths by this survey and was this data source was given an intermediate data weight (Table \ref{tab:dw}). Only a limited number of age data were available in 2022 from the CCFRP Hook and Line survey and were input as conditional-age-at-length data. This data source had a slightly higher proportion of fish observed of small sizes at intermediate ages than the model exception give the estimated growth (Figure \ref{fig:ccfrp-age-pearson})

The CDFW ROV survey observed fish of a large size range and was fit well by the model (Figure \ref{fig:len-agg-fit}). Across the five years with available length data there was no clear pattern of model misfit in the Pearson residuals (Figure \ref{fig:rov-pearson}). The observed mean lengths observed by this survey increased between the two sampling periods (2014-2015 and 2019-2021) and were fit well by the model expectations (Figure \ref{fig:rov-mean-len-fit}).  

The aggregated sexed length composition data from the `r hkl` was fit relatively well by the model (Figure \ref{fig:len-agg-fit}). The Pearson residuals by sex did not show any clear patterns of poor fit (Figure \ref{fig:nwfsc-hkl-pearson}). Notably, there were no patterns of residuals at the larger sizes across sample years indicating that there was not a clear shift in larger fish being observed as the number of MPA and sites within the CCAs began to be sampled. The trend in mean lengths was fit well by the model with both the data and model showing a decline in mean lengths in the mid-2010s and an increase in mean length in recent years (Figure \ref{fig:nwfsc-hkl-mean-len-fit}). The Pearson residuals for the conditional-age-at-length data did not show any clear patterns of poor fits, excluding select positive residuals for single fish observations with length-age combinations (e.g., old-large male in 2012 or older female of intermediate size in 2016, Figures \ref{fig:nwfsc-hkl-age-pearson-1}-\ref{fig:nwfsc-hkl-age-pearson-3}). The generally pattern in the mean ages is generally fit by the model, except for the 2021, which the model underestimates (Figure \ref{fig:nwfsc-hkl-mean-age-fit}).

The NWFSC WCGBT survey across years selected limited numbers of `r spp` off all sizes with the observations of sexed fish being generally well fit by the model (Figure \ref{fig:len-agg-fit}). The Pearson residuals did not show patterns of poor fit across years with the largest residuals arising for small unsexed fish observed in 2016 (Figure \ref{fig:wcgbt-len-pearson}). The mean size observed across years was generally stable although data through 2011 had high variability in the observed length and was fit well by the model (Figure \ref{fig:wcgbt-mean-len-fit}). The conditional-age-at-length data were fit well by the model (Figures \ref{fig:wcgbt-age-pearson-1} and \ref{fig:wcgbt-age-pearson-3}). The mean age across years was fit well by the model with recommended data weights greater than one (i.e., the recommended data weights were capped at one to equal the number of fish, Table \ref{tab:dw} and Figure \ref{fig:wcgbt-mean-age-fit}). 

The Pearson residuals for the Pearson Research and CPFV cooperative collection length data were greatest for the Pearson Research lengths (2005-2007) but the sample sizes across the three years were limited (31 fish total, Figure \ref{fig:coop-len-pearson}). The variance around the mean lengths observed in 2022 was limited but fit well by the model (Figure \ref{fig:coop-mean-len-fit}). The conditional-at-length data from the CPFV cooperative collection were highly variable with positive residuals of smaller than average size-at-age fish compared to other data sources (Figure \ref{fig:coop-age-pearson}). The mean age of 12 for fish observed in 2022 was under-fit by the model (Figure \ref{fig:coop-mean-age-fit}). 

The model estimates generally followed the similar trends in both the recreational CFRS CPFV onboard and CRFS PR dockside indices of abundance (Figures \ref{fig:crfs-cpfv-index-fit} and \ref{fig:crfs-pr-index-fit}). The model estimated vulnerable biomass for the CRFS CPFV onboard index follows the index trend of lower estimates in the beginning of the time series, increasing after 2010, and a subtle decline in the final years of the index. However, the model under-fits select years that increased relative to the surrounding years (e.g., 2007-2008, 2013, and 2018) resulting in the model added additional variance in order to fit these years. The CRFS PR index of abundance had a similar trend that of the CRFS CPFV index and was fit well excluding the the 2007-2008 and the 2012 data points which were under and over estimated, respectively (Figure \ref{fig:crfs-pr-index-fit}).

The model estimated a subtle decline at the end of the time series that fit all but one of the years from the CCFRP Hook and Line survey index of abundance (Figure \ref{fig:ccfrp-index-fit}). The model estimated trajectory followed the trend observed in the CDFW ROV survey that began in 2014, before the CCFRP Hook and Line survey in 2017, with final three year observations of 2019-2021 (Figure \ref{fig:rov-index-fit}). The final survey included in the model was the `r hkl` and the longest fishery-independent time series included in the model. The fit the overall trend of the index well, excluding the 2005 and 2006 data points that were higher than the surrounding years (Figure \ref{fig:nwfsc-hkl-index-fit}).

### Population Trajectory in the Modeled Area

The predicted spawning output for the portion of the stock `r area` is given in Table \ref{tab:south-timeseries} and shown in Figure \ref{fig:ssb}. The predicted spawning output time series shows a slow decline in spawning output from the 1960s
through the mid-1970s as catches ramped up (Figure \ref{fig:catch}). The predicted spawning output sharply decreases until the early 1990s around when catches started to decline from their peak. The spawning output stabilized at low levels through the early 2000s when the population slowly began to slightly increase up until the final years of the model when spawning output is declining. The estimated total biomass follows the same general trend as observed in the spawning output but with more pronounced increase between the early 2000s up until 2018 (Figure \ref{fig:tot-bio}). The estimated spawning output relative to unfished equilibrium spawning output for the sub-area `r area` has remained relatively low between since the late 1980s, peaking in recent years at 0.20 in 2018 (Figure \ref{fig:depl}).

### Population Trajectory for the Stock

```{r, echo=FALSE, results='asis'}

filein = file.path(doc_dir, "shared_text",'33_population.Rmd')
read_child(filein)
```
