## Model Diagnostics

### Convergence

Proper convergence was determined by starting the minimization process from dispersed values of the maximum likelihood estimates to determine if the model found a better minimum. Starting parameters were jittered using the jitter function built into Stock Synthesis, using a jitter input of 0.10. This was repeated 100 times with 17 out of 100 runs returning to the base model likelihood. A better, lower negative log-likelihood, model fit was not found. In the jittering analysis, models with similar log-likelihood values (21 models with difference < 0.50 units) were found with little difference in overall model estimates, indicating a somewhat flat likelihood surface around the maximum likelihood estimate. Additionally, jitters using a smaller jitter value yielded an increased frequency of runs returning to the base model with no models finding a better fit to the data. Through the jittering and the likelihood profiles, we are confident that the base model, as presented, represents the best fit to the data given the assumptions made. There were no difficulties in inverting the Hessian to obtain estimates of variability, although much of the early model investigation was done without attempting to estimate a Hessian.

### Sensitivity Analyses {#sensitivities}

Sensitivity analyses were conducted to examine the relative influence of specific changes to data inputs and model structural assumptions to further address uncertainty associated with the base model estimates and derived management quantities. The majority of the sensitivity models are the result of a single change relative to base model (i.e., they are not the result of cumulative changes such as the modeling approach used with the bridging analysis). Comparisons of likelihood values and estimates of key parameters from the sensitivity analyses are shown in Tables \ref{tab:sensitivities-1}-\ref{tab:sensitivities-3}. Comparison of all sensitivities relative to the base model are shown in Figures \ref{fig:sens-structure} and \ref{fig:sens-data} comparing only select derived quantities relative to the base model. Figures \ref{fig:sens-ssb-1}-\ref{fig:sens-depl-3} show the change in spawning output and the relative spawning output trajectories compared to the base model. Many additional sensitivity runs were explored during development and testing of the base model that are not included here. This section focuses on the main data and structural sensitivity model runs and includes the following:

Structural Sensitivities

\begin{enumerate}
   
  \item  Estimate natural mortality ($M$) for each sex.
  
  \item Estimate steepness ($h$).
  
  \item Estimate $M$ for each sex and $h$.
  
  \item Fix recruitment to be equal to the stock-recruitment curve (no recruitment deviations).
  
  \item Set the CPFV selectivity to be asymptotic for the period of 2004-2022.
  
  \item Add growth platoons that can account for size-dependent survivorship.
  
  \item Remove added variance from all fishery-dependent and -independent indices of abundance (fixed equal to 0.01).
  
  \item Apply Dirichlet data weights.
  
  \item Apply McAllister-Ianelli data weights.

\end{enumerate}

Data Sensitivities

\begin{enumerate}
   
  \item Reduce the PR catch between 1970-1982 to half of the fleet's average catch for that period of time.
  
  \item Eliminate down weighting of the historical CPFV ages (lambda = 1.0).
  
  \item Remove all age data and fix growth at the estimates.
  
  \item Remove the CPFV cooperative collection ages in 2022.
  
  \item Move the CPFV cooperative collection ages to the CPFV fleet and set lambda = 1.0 for CPFV ages.
  
  \item Remove the NWFSC WCGBT survey lengths and ages.
  
  \item Add the NWFSC WCGBT survey index of abundance.
  
  \item Remove all fishery-dependent indices of abundance.
  
  \item Remove the CCFRP Hook and Line survey data (index, lengths, and ages).
  
  \item Add the CDFW ROV survey data (index and lengths).
  
  \item Remove the NWFSC Hook and Line survey data (index, lengths, and ages).
  
  \item Remove the NWFSC Hook and Line survey age data only.
  
  \item Remove the NWFSC Hook and Line survey length and age data (retain only the index of abundance).
  
  \item Move NWFSC Hook and Line survey data prior to the sampling expansion to include CCAs in 2014 to be associated with the Pearson Research Cooperative Collection growth fleet. This approach has been applied in other assessments where the expansion into the CCA were thought to impact the size and age of fish being encountered by the survey. 
  
  \item Remove the NWFSC Hook and Line survey index of abundance (retain the lengths and ages).
  
  \item Remove the NWFSC Hook and Line and CCFRP Hook and Line survey (indices, lengths, and ages).

\end{enumerate}

Across all the sensitivities conducted only a subset resulted in distinct changes in the model estimates and the discussion here will focus on the sensitivities that were identified in Figures \ref{fig:sens-structure} and \ref{fig:sens-data}. The sensitivity that did not estimate annual recruitment deviations and predicted recruitment directly from the stock-recruitment curve resulted in the model estimating a higher initial unfished recruitment ($R_0$), a higher spawning output in the final model year, and a less depleted population `r area` (Table \ref{tab:sensitivities-1}, Figures \ref{fig:sens-ssb-1} and \ref{fig:sens-depl-1}). The dynamics of `r spp` `r area` appear to be driven by strong or weak recruitment variations combined with exploitation. In order to fit the data in the absence of recruitment variation the model needs to adjust the derived quantities accordingly.  

Both sensitivities that explored the impact of alternative data weighting methodologies resulted in differences relative to the base model in derived final spawning output and relative spawning output (Table \ref{tab:sensitivities-1}, Figures \ref{fig:sens-ssb-1} and \ref{fig:sens-depl-1}). The suggested data weights from the Dirichlet methodology for most data types hit the upper bound on data-weighting of 1.0 (Table \ref{tab:dw}). These suggested data weights for the length data may be due to the input sample sizes not being equal to the number of fish sampled and if the data processing were revised, the suggested data weights may be less than those estimated here. However, the Dirichlet data weighting approach also estimated data weights at the upper bound of 1.0 for the majority of age data sources which in most instances had an input sample size equal to the number of fish. Similar behavior in data weights suggested by the Dirichlet method have been encountered by sensitivities for other groundfish assessments (e.g. petrale sole in 2019, `r spp` in 2021). In order to understand what is behind this behavior, additional simulation work should be conducted to inform how this approach should be best applied. The other data weighting approach, McAllister-Ianelli, also estimated a higher final spawning output and relative status compared to the base model (Table \ref{tab:sensitivities-1}, Figures \ref{fig:sens-ssb-1} and \ref{fig:sens-depl-1}). Much of the exploratory modeling work conducted for this assessment used either Francis or McAllister-Ianelli. Models that used the McAllister-Ianelli data-weighting for `r spp` `r area` seemed to generally have issues converging to the true maximum likelihood estimate (MLE, e.g., jitter commonly identified a model with a lower MLE) with this issue also extending to challenges when conducting likelihood profiles. These issues were encountered when running diagnostics for this alternative model where the jittering revealed an inability of the MLE being repeatedly identified (i.e., out of 100 jitters run at a level of 0.10, only one run returned to the true MLE) and likelihood profiles across parameters failing to converge to a reasonable model across parameter values.

The model showed sensitivity to a range of data sources (Figure \ref{fig:sens-data}). Removing the length and age data from the `r wcgbt` resulted in a larger estimate of final spawning output and a less depleted population (Table \ref{tab:sensitivities-2}, Figures \ref{fig:sens-ssb-2} and \ref{fig:sens-depl-2}). These data had a number of observations from age-0 and age-1 `r spp` and when removed from the model the size-at-age 2 increased for female fish relative to the base model resulting in a meaningful change in the growth curve. Removing both CRFS CPFV and PR indices of abundance from the model also resulted in the sensitivity estimating a larger final spawning  output (Table \ref{tab:sensitivities-2}, Figures \ref{fig:sens-ssb-2} and \ref{fig:sens-depl-2}). The majority of the indices included in the model included a slight downturn at the end of the time series (Figure \ref{fig:stand-cpue}) indicating that each of these indices have some level of contribution to the estimates at the end of the time series.  

The base model was most sensitive to the removal of the `r hkl` data (i.e., indices, lengths, and ages, Figure \ref{fig:sens-data}). The `r hkl` is the only major data source in the model that had asymptotic selectivity (i.e., the commercial dead fleet selectivity was also asymptotic but given the low removals was not a influential fleet in the model, Table \ref{tab:sensitivities-3}, Figures \ref{fig:sens-ssb-3} and \ref{fig:sens-depl-3}). Removing all data from this survey allows the model to estimate a lower size-at-age 20 for both male and female fish which may allow the model to estimate a less depleted population. Explorations that removed the age data from this survey indicated that the change in model estimates relative to the base model are largely being driven by the age-composition data from this survey. 

### Retrospective Analysis

A five-year retrospective analysis was conducted by successively removing years of data ranging from 2017 - 2021 (i.e., “Data -1 Years” corresponds to data through 2021). The estimated spawning output for all retrospectives was higher at the start of the time series and lower for the final model years (Figure \ref{fig:retro-ssb}). There are a substantial number of ages only available in 2022 which may be a contributing factor leading to this slight decline in estimated spawning output when the most recent data were removed. Additionally, removing five years of data removes all but one year of data from the CCFRP Hook and Line survey and two years from the CDFW ROV survey. The estimates of relative spawning output to unfished for the population `r area` decreased with each subsequent data peel compared to the base model but were within the uncertainty intervals  (Figure \ref{fig:retro-depl}).

### Likelihood Profiles

Likelihood profiles were conducted for $R_0$, steepness, and sex-specific natural mortality values separately. These likelihood profiles were conducted by fixing the parameter at specific values and estimating the remaining parameters based on the fixed parameter value. The priors for all parameters, including the parameter being profiled, were included in every likelihood model. For example, including the prior on natural mortality across the profiled values of natural mortality provides information on the likelihood contribution of that prior as if it were estimated in the model.  

The negative-log-likelihood was minimized at a log($R_0$)value of `r round(model$estimated_non_dev_parameters[rownames(model$estimated_non_dev_parameters) == "SR_LN(R0)", "Value"], 2)` (Figure \ref{fig:r0-profile}). The likelihood profile for $R_0$ was most informed by the recruitment likelihood contribution within the model. The information about $R_0$ across the other data sources was limited with the age data having the greatest information supporting lower values of $R_0$. Across the range of log($R_0$) values profiled the spawning output at the end of the time series were similar with the largest differences occurring around the estimates of unfished spawning output (Figure \ref{fig:r0-ssb}). The varying estimates of unfished spawning output across values of log($R_0$) translated to variations in the ending population status (11-22 percent), although all of the profile trajectories ended in a similar relative spawning output range as the base model (Figure \ref{fig:r0-depl}).  

The majority of data types included in the model contained limited information on steepness (Figure \ref{fig:h-profile}). The minimum identified by the profile of approximately 0.69, was very similar to the fixed value in the model (0.72) based on the mean of the prior but values between approximately 0.60-0.80 had similar support from the data. The sensitivity that explored estimating steepness indicated little to no change in the negative-log-likelihood relative to the base model that fixes this parameter (Table \ref{tab:sensitivities-1}). Similar to the profile over log($R_0$), fixing steepness in the model at values ranging between 0.30-0.95 had the largest impact on the derived unfished spawning output resulting in a range of relative spawning outputs between 12-23 percent of unfished for the sub-area `r area` (Figures \ref{fig:h-ssb} and \ref{fig:h-depl}).

Parameter profiles across a range of female natural mortality values indicated that the negative-log-likelihood was minimized around values below the model fixed value of 0.108 yr^-1^ (Figure \ref{fig:m-profile}). The length data were the most informative around this parameter with the length data from the CDFW ROV and NWFSC Hook and Line surveys contributing the most information about natural mortality. The information in the age data by source was more limited but the aggregate information across data sources supported values greater than 0.09 yr^-1^. Relative to the other parameter profiles the assumed value of female natural mortality had a reduced impact on the estimates of spawning output and the relative status (Figures \ref{fig:m-ssb}-\ref{fig:m-depl}). The range of relative spawning output at the end of the time series was between 8-16 percent of unfished spawning output across natural mortality values between 0.08-0.12 yr^-1^. 

Throughout model explorations estimates of both steepness and natural mortality were made. A decision to not estimate these parameters in the base model was based on the change in the negative-log-likelihood of only 1.5 units when the three additional parameters were estimated.  Additionally, these parameters were not well informed by the data and appeared to lead to issues with the model correctly identifying the best fit to the data.

### Historical Analysis

The estimated spawning output from both the 2013 and 2021 assessments for the portion of `r spp` `r area` compared to the base model are shown in Figures \ref{fig:comp-assess-sb} and \ref{fig:comp-assess-depl}. The model structure and the approach used in the 2013, index-based data-moderate assessment using Extended-Depletion-Based Stock Reduction Analysis, was substantially different both from the 2021 and this assessment. The 2013 assessment assumed fecundity was equal to weight-at-length while the 2021 assessment and the base model sets fecundity in numbers of eggs as a function of length, so estimates of total biomass are shown in Figure \ref{fig:comp-assess-sb} to allow comparability. The estimated scale of the population and relative fraction of spawning output among the 2021 and this base model were consistent despite the number of additional data sources, changes in biology (estimated vs. fixed at external estimates), and recruitment dynamics (estimation of annual recruitment deviations in the base model which were fixed to 0 in the 2021 assessment).    

