\clearpage
# Figures

<!-- ====================================================================== --> 
<!-- *******************    Assessment Map      *************************** --> 
<!-- ====================================================================== --> 


<!-- ====================================================================== -->  
<!-- ****************** Catches Used in the Model ************************* --> 
<!-- ====================================================================== -->  

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "catch2 landings stacked.png"), 
caption = "Landings by fleet used in the base model where catches in metric tons by fleet are stacked",
label = 'catch')
```	

<!-- ====================================================================== --> 
<!-- ******************* Data Used in the Model *************************** --> 
<!-- ====================================================================== --> 

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "data_plot.png"), 
caption = "Summary of data sources used in the base model",
label = 'data-plot')
```	

<!-- ======================================================= -->
<!-- *************** Commercial Data *********************** --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_bubflt1mkt0_page2.png"), 
caption = "Length composition data from the commercial dead fleet",
label = 'com-dead-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_data_weighting_TA1.8_Commercial_dead.png"), 
caption = "Mean length for commercial dead fleet with 95 percent confidence intervals",
label = 'mean-com-dead-len-data')
```



```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_bubflt2mkt0.png"), 
caption = "Length composition data from the commercial live fleet",
label = 'com-live-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_data_weighting_TA1.8_Commercial_live.png"), 
caption = "Mean length for commercial live fleet with 95 percent confidence intervals",
label = 'mean-com-live-len-data')
```



<!-- ======================================================= -->
<!-- ************* Recreational Data *********************** --> 
<!-- ======================================================= -->



```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_bubflt3mkt0_page2.png"), 
caption = "Length composition data from the recreation CPFV fleet",
label = 'rec-cpfv-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_data_weighting_TA1.8_Rec_CPFV.png"), 
caption = "Mean length for recreational CPFV fleet with 95 percent confidence intervals",
label = 'mean-rec-cpfv-len-data')
```




```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_bubflt4mkt0_page2.png"), 
caption = "Length composition data from the recreation PR fleet",
label = 'rec-pr-len-data')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_data_weighting_TA1.8_Rec_Private.png"), 
caption = "Mean length for recreational PR fleet with 95 percent confidence intervals",
label = 'mean-rec-pr-len-data')
```



<!-- ======================================================= -->
<!-- ***************  NWFSC HKL Survey   ******************* --> 
<!-- ======================================================= -->


```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "nwfsc_hkl", "maps", "Map_HL_Sites_lndscp.jpg"), 
caption = "Area sampled by the NWFSC Hook and Line survey",
label = 'nwfsc-hkl-map')
```



```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "nwfsc_hkl", "plots", "hkl_copper_by_site_count_all_years.png"), 
caption = "Observations of copper rockfish by the NWFSC Hook and Line survey by sample area, inside and outside Cowcod Conservation areas (CCA)",
label = 'nwfsc-hkl-site')
```



```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir,  "nwfsc_hkl", "plots", "standardized_cpue_nwfsc_hkl_inside_outside.png"), 
caption = "Standardized CPUE inside and outside the CCA.",
label = 'nwfsc-hkl-cca-main')
```



```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir,  "nwfsc_hkl", "plots", "nwfsc_hkl_observations_by_depth.png"), 
caption = "Number of observations by depth (m) inside and outside the CCAs.",
label = 'nwfsc-hkl-depth')
```



```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "survey_indices", "nwfsc_hkl", "rstan_full_nb_glm_year_site_drop_swell_bocaccio_vermilon", "Index.png"), 
caption = "Estimated index of abundance for copper rockfish.",
label = 'nwfsc-hkl-index-main')
```



```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "nwfsc_hkl", "plots", "hkl_observations_by_length_sex_area.png"), 
caption = "Observed length (cm) distribution of copper rockfish by the NWFSC Hook and Line survey by sample area, inside and outside Cowcod Conservation areas (CCA)",
label = 'nwfsc-hkl-site-len')
```



```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "nwfsc_hkl", "plots", "nwfsc_hkl_age_at_length.png"), 
caption = "Age and length by sex for copper rockfish in the NWFSC Hook and Line survey.",
label = 'nwfsc-hkl-len-age')
```



```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_bubflt7mkt0.png"), 
caption = "Length composition data from the NWFSC Hook and Line survey",
label = 'hkl-len-data')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_data_weighting_TA1.8_NWFSC_HKL.png"), 
caption = "Mean length for NWFSC Hook and Line survey with 95 percent confidence intervals",
label = 'mean-hkl-len-data')
```


<!-- ======================================================= -->
<!-- ***************     ROV             ******************* --> 
<!-- ======================================================= -->



```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(data_dir, "survey_indices", "rov", "plots", "rov_transect_collapsed_copper_south_protection_count.png"), 
caption = "The location and size of observations across all years and transects.",
label = 'rov-obs-loc')
```



```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(data_dir, "survey_indices", "rov", "plots", "south_raw_cpue_by_mpa_group.png"), 
caption = "The trend of the calculated CPUE by each MPA and Reference group.",
label = 'rov-raw-cpue')
```



```{r, results = 'asis'}
sa4ss::add_figure(
filein = file.path(data_dir, "survey_indices", "rov", "plots", "rov_length_by_area_designation.png"), 
caption = "The distribution of lengths across all years for MPA and Reference area north and south of Point Conception.",
label = 'rov-len')
```




```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_bubflt6mkt0.png"), 
caption = "Length composition data from the CDFW ROV survey",
label = 'rov-len-data')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "comp_lendat_data_weighting_TA1.8_CDFW_ROV.png"), 
caption = "Mean length for the CDFW ROV survey with 95 percent confidence intervals",
label = 'mean-rov-len-data')
```




<!-- ======================================================= -->
<!-- ***************     CCFRP           ******************* --> 
<!-- ======================================================= -->



<!-- ======================================================= -->
<!-- ***************  NWFSC WCGBT Survey  ****************** --> 
<!-- ======================================================= -->

```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "wcgbt", "south", "plots", "cpue_map.png"), 
caption = "Location and catch-per-unit-effort by location caught south of Point Conception by the NWFSC WCGBT survey.",
label = 'wcgbt-cpue')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "wcgbt", "south", "plots", "presence-absence_proportion_by_depth.png"), 
caption = "Number of positive tows across all years by depth in meters.",
label = 'wcgbt-depth')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "wcgbt", "plots", "wcgbt_south_age_at_length_by_area.png"), 
caption = "Age and length by sex for copper rockfish caught south of Point Conception by the NWFSC WCGBT survey.",
label = 'wcgbt-len-age')
```



<!-- ======================================================= -->  
<!-- ******************   Biology  ************************* --> 
<!-- ======================================================= -->  



```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "bio6_maturity.png"), 
caption = "Maturity as a function of length",
label = 'maturity')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "bio9_fecundity_len.png"), 
caption = "Fecundity as a function of length",
label = 'fecundity')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "wcgbt", "plots", "length_fraction_female.png"), 
caption = "Fraction of each sex by length by the NWFSC WCGBT survey",
label = 'frac-sex-len')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "biology", "plots", "Length_Weight_All.png"), 
caption = "Estimated weight-at-length",
label = 'weight-length')
```



```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "ages", "ageing_error", "B0_S3", "Reader_1_vs_Reader_2.png"), 
caption = "Distribution of double reads between age reader 1 and 2.",
label = 'age-error-dist')
```


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots",  "numbers5_ageerrorSD.png"), 
caption = "Ageing imprecision standard deviation of observed age in years.",
label = 'age-error')
```



```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots",  "numbers10_ageerror_matrix_1.png"), 
caption = "Distribution of observed age at true age for ageing error type 1.",
label = 'age-error-matrix')
```


<!-- ======================================================= -->  
<!-- ******************   Bridge   ************************* --> 
<!-- ======================================================= -->


```{r, results = 'asis'}
add_figure(
filein = file.path(bridge_dir, "_plots", "0_model_convert_compare2_spawnbio_uncertainty.png"),
caption = "Model version bridge comparison of estimated spawning output",
label = 'bridge-ssb')
```

```{r, results = 'asis'}

add_figure(
filein = file.path(bridge_dir, "_plots", "0_model_convert_compare4_Bratio_uncertainty.png"),
caption = "Model version bridge comparison of estimated fraction unfished",
label = 'bridge-depl')
```


<!-- ====================================================================== -->
<!-- *********************    Priors            ********************** --> 
<!-- ====================================================================== -->

<!-- ====================================================================== -->
<!-- *********************  Model Est. Biology       ********************** --> 
<!-- ====================================================================== -->

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "bio1_sizeatage.png"),
caption = "Model estimated length-at-age in the beginning of the year. Shaded area indicates 95 percent distribution of length-at-age around the estimated growth curve",
label = 'mod-est-len-age')
```

<!-- ====================================================================== -->
<!-- *********************    Selectivity            ********************** --> 
<!-- ====================================================================== -->




<!-- ======================================================= -->  
<!-- ****************** Recruitment ************************ --> 
<!-- ======================================================= -->


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "ts11_Age-0_recruits_(1000s)_with_95_asymptotic_intervals.png"), 
caption = "Estimated time series of age-0 recruits (1000s)",
label = 'recruits')
```

```{r, results = 'asis'}
#add_figure(
#filein = file.path(model_dir, "plots", "recdevs2_withbars.png"), 
#caption = "Estimated time series of recruitment deviations",
#label = 'rec-devs')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "SR_curve.png"), 
caption = "Stock-recruit curve. Point colors indicate year, with warmer colors indicating earlier years and cooler colors in showing later years",
label = 'bh-curve')
```



<!-- ====================================================================== -->
<!-- ****************** Fit to the Index Data  **************************** --> 
<!-- ====================================================================== -->





<!-- ======================================================= -->  
<!-- ****************** Time Series ************************ --> 
<!-- ======================================================= -->


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "ts7_Spawning_output_with_95_asymptotic_intervals_intervals.png"), 
caption = "Estimated time series of spawning biomass",
label = 'ssb')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "ts1_Total_biomass_(mt).png"), 
caption = "Estimated time series of total biomass",
label = 'tot-bio')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "ts9_Relative_spawning_output_intervals.png"), 
caption = "Estimated time series of fraction of unfished spawning biomass",
label = 'depl')
```


<!-- ====================================================================== -->
<!-- ******************    Reference Points    **************************** --> 
<!-- ====================================================================== -->


```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "SPR2_minusSPRseries.png"), 
caption = "Estimated 1 - relative spawning ratio (SPR) by year",
label = '1-spr')
```

\clearpage

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "SPR4_phase.png"), 
caption = "Phase plot of the relative biomass (also referred to as fraction unfished) versus the SPR ratio where each point represents the biomass ratio at the start of the year and the relative fishing intensity in that same year. Lines through the final point show the 95 percent intervals based on the asymptotic uncertainty for each dimension. The shaded ellipse is a 95 percent region which accounts for the estimated correlations between the biomass ratio and SPR ratio",
label = 'phase')
```

```{r, results = 'asis'}
add_figure(
filein = file.path(model_dir, "plots", "yield2_yield_curve_with_refpoints.png"), 
caption = "Equilibrium yield curve for the base case model. Values are based on the 2020
fishery selectivities and with steepness fixed at 0.80",
label = 'yield')
```
