# Appendix B. MRFSS CPFV Dockside Index of Abundance {#mrfss-cpfv-index}

```{r, echo=FALSE, results='asis'}

filein = file.path(doc_dir, "shared_text",'21f_mrfss_index.Rmd')
read_child(filein)
```

From 1980 to 2003 the MRFSS program conducted dockside intercept surveys of the 
recreational CPFV fishing fleet. No MRFSS CPUE data are available for the years 
1990-1992, due to a hiatus in sampling related to funding issues. Sampling of 
California CPFVs north of Point Conception was further delayed, and CPFV samples 
in 1993 and 1994 are limited to San Luis Obispo County. 
For purposes of this assessment, the MRFSS time series was truncated at 1999 due 
to sampling overlap with the 
onboard observer program, i.e., the same observer samples the catch while 
onboard the vessel and also conducts the dockside intercept survey for 
the same vessel.  The onboard observer data provide higher resolution data of retained 
and discarded catch.

Each entry in the RecFIN Type 3 database corresponds to a 
single fish examined by a sampler at a particular survey site. Since only a 
subset of the catch may be sampled, each record also 
identifies the total number of that species possessed by the group of anglers 
being interviewed.  The number of anglers and the hours fished are also recorded. 
The data, as they exist in RecFIN, do not indicate which records 
belong to the same boat trip. A description of the algorithms and process used to 
aggregate the RecFIN records to the trip level is outlined in the Supplemental Materials 
(“Identifying Trips in RecFIN”).

Trips recorded with a primary area fished in Mexico or in bays, e.g., 
San Francisco Bay, were excluded before any filtering on species composition.
For indices representing only north of Point Conception, the years 1993-1994 were 
excluded due to limited spatial coverage.

The Stephens-MacCall [-@stephens_multispecies_2004] filtering approach was used to predict the 
probability of catching copper rockfish, based 
on the species composition of the sampler examined catch in a given trip. Prior 
to applying the Stephens-MacCall filter, we identified potentially informative 
predictor species, i.e., species with sufficient sample sizes and temporal coverage 
(present in at least 5\% of all trips) to inform the binomial model.  The remaining 
 xx species all co-occurred with copper rockfish in at least one trip 
and were retained for the Stephens-MacCall logistic regression. Coefficients 
from the Stephens-MacCall analysis (a binomial GLM) are positive 
for species that are more likely to co-occur with copper rockfish, 
and negative for species that are less likely to be caught with copper rockfish 
(Figure \@ref(fig:fig-sm-mrfss)).
The top five species with high probability of co-occurrence with copper rockfish include
copper, greenspotted, bocaccio, and olive rockfishes and ocean whitefish, all of which are associated with rocky reef and kelp 
habitats. The five species with the lowest probability of co-occurrence were 
kelp bass, Pacific bonito, white croaker, California sheephead, and barred sandbass.

While the filter is useful in identifying co-occurring or non-occurring species 
assuming all effort was exerted in pursuit of a single target, the targeting of 
more than one species or species complex ("mixed trips") can result in co-occurrence of species in the catch that do not truly co-occur in terms of habitat
associations informative for an index of abundance. Stephens and MacCall 
[-@stephens_multispecies_2004] recommended including all trips above a threshold where the 
false negatives and false positives are equally balanced.  However, this does 
not have any biological relevance and for this data set, and we assume that if a 
copper rockfish was landed, the anglers fished in appropriate habitat, 
especially given copper rockfish is strongly associated with rocky habitat.


Stephens and MacCall [-@stephens_multispecies_2004] proposed filtering (excluding) trips from the index 
standardization based on a criterion of balancing the number of false positives 
and false negatives. False positives (FP) are trips that are predicted to catch 
a copper rockfish based on the species composition of the catch, but did not. False 
negatives (FN) are trips that were not predicted to catch a copper rockfish, given the 
catch composition, but caught at least one. The Stephens-MacCall filtering method identified the probability of occurrence at which the rate of "false 
positives" equals "false negatives" of 0.31. The 
trips selected using this criteria were compared to an alternative method 
including all the "false positive" trips, regardless of the probability of 
encountering copper rockfish. 
This assumes that if copper rockfish were caught, the anglers must have fished in 
appropriate habitat during the trip. The catch included in this index is 
"sampler-examined" and the samplers are well trained in species identification.


The threshold probability that balances FP and FN excludes 
5383 trips that did not catch a copper rockfish (84% 
of the trips), and 308 trips (5% of the data) that 
caught a copper rockfish. We retained the latter set of trips (FN), assuming that 
catching a copper rockfish indicates that a non-negligible fraction of the fishing 
effort occurred in habitat where copper rockfish occur. Only “true negatives” 
(the 5383 
trips that neither caught copper rockfish, nor were predicted to catch them by the model) 
were excluded from the index standardization. The final dataset selected included 
1043 trips, 70% 
of which encountered copper rockfish.  Sample sizes by the factors selected to model are in Tables 
\@ref(tab:tab-region-mrfss) and \@ref(tab:tab-year-mrfss).


Initial exploration of negative binomial models for this dataset proved to be 
ill-fitting. The proportion of zeroes predicted by the Bayesian negative binomial 
models were different enough from the fraction of zeroes in the raw data, that 
a negative binomial model was not considered for model selection. We modeled catch 
per angler hour (CPUE; number of fish per angler hour) with a Bayesian delta-GLM model. 
Models incorporating temporal (year, 2-month waves) 
and geographic (region and primary area fished (inshore <3 nm, offshore >3 nm) 
factors were evaluated. For assessments north of Point Conception, two regions were defined based on counties, 1) Del Norte 
to Santa Cruz ("N") and 2) Monterey to San Luis Obispo ("C"). For assessment models south 
of Point Conception, the region represents individual counties. Note that Santa Barbara 
county spans north and south of Point Conception, but all accessible fishing ports in Santa Barbara county are south of Point Conception and vessels rarely (if ever) transit Point Conception.  Indices with a year and area interaction were not considered in model selection; trends in the average CPUE by region were similar in the filtered data set (Figure \@ref(fig:fig-areacpue-mrfss)). 

<!--For models that span counties north and south of Pt. Conception, Santa Barbara to 
San Diego counties compose a third region ("S"). 
-->

The positive observations were modeled with a Lognormal distribution 
that was selected over a Gamma model
by a $\Delta AIC$ of 51.8, and supported by Q-Q plots of the positive observations fit to both distributions (Figure \@ref(fig:fig-dist-fits-mrfss)).  The delta-GLM
method allows selection of differing linear predictors between the binomial and positive models. Based on AIC values from maximum likelihood fits, 
