# Appendix F. NWFSC Hook and Line Index of Abundance

Since 2004, the NWFSC has conducted an annual hook and line survey targeting shelf rockfish in the genus *Sebastes* at fixed stations (e.g., sites, Figure \ref{fig:nwfsc-hkl-map}) in the Southern California Bight. Key species of rockfish targeted by the `r hkl` are bocaccio (*S. paucispinis*), cowcod (*S. levis*), greenspotted (*S. chlorostictus*), and vermilion/sunset (*S. miniatus* and *S. crocotulus*) rockfishes, although a wide range of rockfish species have been observed by this survey. During each site visit, three deckhands simultaneously deploy 5-hook sampling rigs (this is referred to as a single drop) for a maximum of 5 minutes per line, but individual lines may be retrieved sooner at the angler's discretion (e.g., to avoid losing fish). Five drops are attempted at each site for a maximum possible catch of 75 fish per site per year (3 anglers x 5 hooks x 5 drops). Further details regarding the sample frame, site selection, and survey methodology are described by Harms et al. [-@harms_noaa_2008]. 

From 2004 through 2013, sampling was conducted only outside the Cowcod Conservation Areas (CCAs). Beginning in 2014, 40 sites inside the CCAs were sampled, and roughly another 40 sites have been added in subsequent years inside the CCAs. The survey currently has 201 sites (79 inside and 122 outside the CCAs).`r Spp` have been observed at multiple sampling sites by the `r hkl` each year between 2004 - 2022 (Table \ref{tab:nwfsc-hkl-obs}).  Starting in 2014 the `r hkl` added sampling sites located within the cowcod conservation area (CCA). Across all sample years and sample sites the `r hkl`  has observed a total of 1,198 `r spp` with all but 4 fish identified down to sex. While `r spp` have been observed both outside and inside the CCA (Figures \ref{fig:nwfsc-hkl-site}), the vast majority of observations of `r spp` have been in open areas (1,097 observations).  The limited number of `r spp` observations within the CCA, a total of 101 fish, constrained the ability to determine whether the CCA impacted the frequency and or sizes observed compared to the opens areas sampled. `r Spp` were observed at sites with depth ranging between 40 - 120 m.

While `r spp` have not been encountered is large numbers similar to some of the other commonly encountered species (vermilion/sunset, bocaccio, greenspotted rockfish) in the `r hkl`, `r spp` has been observed every year that the survey has been conducted (Table \ref{tab:nwfsc-hkl-pos-year}). Observations of `r spp` commonly occur across a range of depths between 30 - 120 m with observations peaking around 80 m (Table \ref{tab:nwfsc-hkl-pos-depth}). The `r hkl` extended its sampling to include sites within CCA beginning in 2014 and the number of observation of `r spp` at CCA sites have been limited (Table \ref{tab:nwfsc-hkl-obs}). 

The sites considered for the creation of a relative index of abundance were limited to sites that have caught at least 1 `r spp` across all years. A range of alternative model structures to generate an index of abundances. This included alternative levels of aggregation (hook, drop, or site), probability distributions (negative binomial, delta-gamma, or delta-lognormal), and covariates (year, site number, depth, swell height, inside/outside CCA, and/or the number of vermilion/sunset or bocaccio rockfishes observed, Table ref{tab:nwfsc-hkl-model-selection}). All modeling was conducted using sdmTMB [@anderson_sdmtmb_2022]. The final selected model was a negative binomial model that included covariates terms for year, site number, drop, swell height, and the number of bocaccio and vermilion/sunset rockfishes separately. Excluding or including observations within the CCA had little impact on the overall trend and uncertainty in the indices, however, excluding the observations within the CCA resulted in a slightly lower scale in the relative index (Figure \ref{fig:nwfsc-hkl-indices}). Additionally, the overall trend in the index of abundance were highly similar across the explored probability distributions. 


\input{tex_tables/nwfsc_hkl_positive_samples_by_year.tex}

\input{tex_tables/nwfsc_hkl_positive_samples_by_depth.tex}

\input{tex_tables/nwfsc_hkl_sample_number_by_site_cca.tex}

\input{tex_tables/nwfsc_hkl_model_selection.tex}


```{r, results = 'asis'}
add_figure(
filein = file.path(data_dir, "survey_indices", "nwfsc_hkl", "plots", "index_comparison.png"), 
caption = "Comparison of estimated relative indices of abundance exploring alternative probability distributions and covariates.",
label = 'nwfsc-hkl-indices')
```
