## Information Provided by the Commercial and Recreational Fleet Representatives


The copper rockfish STAT held the following three informal virtual meetings with stakeholders as part of the data exploration process:

\begin{enumerate}

  \item Copper Rockfish and the Commercial Fisheries on January 10, 2023 (24 attendees)
  \item Copper Rockfish and the Recreational Fishery South of Point Conception on January 23, 2023 (17 attendees)
  \item Copper Rockfish and the Recreational Fishery North of Point Conception on January 30, 2023 (19 attendees)
  
\end{enumerate}


A summary of the information learned from these meetings is provided here. We would like to thank everyone who participated in our virtual meetings for their willingness to participate in the stock assessment process and provide additional insight into the fisheries for copper rockfish.

### Preferred Habitat and Life History Notes

Copper rockfish are "king" of the reef and appear to push other species off of the best habitat within a reef. The STAT consistently heard from all fishermen that copper rockfish are not caught in areas of high relief. Copper rockfish prefer areas of flatter or broken hard bottom, and also venture out over soft bottom habitat. Larger fish are often caught over soft bottom where they are feeding on sanddabs. Copper rockfish do not feed on pyrosomes as frequently as other rockfish species.  Copper rockfish will follow prey targets, including pelagic red crabs that have been observed farther north than usual. In general, rockfish catches decreased when prey (anchovies, squid, mychtophids, pyrosomes, etc.) are hyper-abundant. Fishermen notice ontogenetic shifts, as well as seasonal and weather related movements of copper rockfish. Copper rockfish also tend to move based on weather conditions. North of Point Conception (\PtC), copper rockfish cannot be found during bad weather and seem to move to deeper waters. This appears true of all rockfish in general with respect to long period swells that create heavy bottom surge, increased turbulence and suspend flocculant materials near the bottom. 

### Commercial Fishery

A Deeper Nearshore permit is needed to fish copper rockfish commercially in California.  The trip limits of 75 pounds per two-month period, in combination with depth restrictions, have negatively impacted the commercial targeting of copper rockfish. The fleet is releasing by descending back to depth more fish now with the current lower quotas. Copper rockfish are a component of the live fish fishery in both northern and southern California. They are most often targeted to be sold live, but those fish that do not survive well are sold dead at a much lower price. 
Copper rockfish are encountered at an average depth of 45 fm, but can be found out to 60 fm. 

The live fish market is constantly in flux and can be difficult to predict. In southern California, a large portion of the live-fish fishery collapsed during the COVID-19 pandemic and has not returned. A fisherman's market in San Diego has allowed individual fishermen to sell fish directly to the public. Many of the live fish buyers in central California transport live fish to Las Vegas, Nevada or Los Angeles and San Jose in California. 

North of Point Conception, copper rockfish is a target of the commercial fleet. North of Cape Mendocino (\CapeM), live copper rockfish sell for 3-4 times the price of dead. For fishermen targeting black rockfish in the north, copper rockfish are an incidental catch of value.  Out of Morro Bay, copper rockfish ranging between 1 to 6 pounds are most common in the 10-15 fm range and also sell for $7 to $8 per pound. In shallow waters, fishermen will use traps within the live-fish fleet and vertical gear for deeper waters. In Central California (near Morro Bay) the nearshore live-fish target species live in the kelp beds and larger copper rockfish are on the outside edges of the reef. Larger coppers are typically found on isolated outcrops. It's rare for the commercial live fleet to fish deeper than 15 fm, and in central California it's harder to keep fish exhibiting barotrauma alive. The price of live fish is much higher.

Commercial fishermen from multiple areas along the coast emphasized that the price differential for copper by size is not as pronounced as it is for other species landed in the live-fish fishery. North of San Francisco, the commercial fleet encounters larger copper rockfish (~ 7 pounds) in general.  Fish smaller than 2.5 - 3 pounds (approximately 14-17 inches) are desired by the live-fish buyers and the restaurant market and thus will sell for a higher price. The larger fish can be retailed to the general public.

South of Point Conception, copper rockfish are not generally a target species for the live-fish fishery and have been difficult to market. The fleet is now marketing copper rockfish in Southern California as a species similar to the popular "grouper" (bocaccio rockfish, *S. paucispinis*) and demand is increasing. The majority of commercially caught copper rockfish in Southern California are sold dead.  The price of a dead copper in San Diego is around $6 per pound. The fleet can keep copper alive from depths as deep as 60 fathoms with no issue. Coppers seem to be the hardiest of the rockfish species. 


### Recreational Fishery

In 1997 there were approximately 295 CPFVs in California and in 2022 that number was reduced to 193 active Coast Guard inspected CPFVs, defined as vessels that can carry seven or more passengers. Of the 193 CPFVs in the state, 78 fish offshore exclusively. The number of active six-pack vessels is much less.

During the COVID-19 pandemic, reduced loads were required on the CPFVs to maintain distancing among passengers. Customers preferred the reduced loads that resulted in a less crowded vessel and have been willing to pay the increased charter costs to maintain the reduced loads post-COVID. This is true along the entire coast of California for Coast Guard inspected vessels.

#### North of Point Conception

The majority of vessels north of Bodega Bay are six-packs. Vessels fishing out of Eureka generally fish closer to shore due to weather and fuel costs. The primary target in this area is salmon, and vessels will switch to rockfish especially if salmon are not biting or salmon season is closed.

Larger copper rockfish can be found in 40-60 feet of water and swell is a good indicator for the presence of copper rockfish. If there is swell, the copper rockfish remain close to the bottom and are not as active, i.e., there is a reduced chance of catching copper rockfish.  In Eureka, copper rockfish are a desirable species in the recreational fleet due to their larger average size. Copper rockfish would not be caught more than 5-10 feet off the bottom. 

In central California, small copper rockfish can be found in 100+ feet of water at the edge of the Farallon Islands. The last two to three weeks of December, fishermen out of Emeryville, California find aggregations of copper rockfish on shale beds where they are not usually present.

Small copper rockfish have been caught off the the jetties in Humboldt, Pillar Point Harbor, and San Francisco, California. In the Half Moon Bay CFPV fleet, copper rockfish are rarely observed shallower than 35 fathoms and they tend to only bite the bottom hook. Stakeholder reported that the gear regulations from unlimited hooks to two hooks per line and a one pole limit in 1999-2000 resulted in increased loss of fish to sea lions. 

#### South of Point Conception

After the depth restrictions and other closures, the fleet moved to different fishing grounds and the desire for copper rockfish increased retention. Over half of the habitat regularly fished by the 1/2-day vessels out of Mission Bay in San Diego is now within in protected areas closed to fishing, and the depth closures moved effort from offshore to inshore (<50-60fa) starting in 2001. During the summer months the effort of the fleet in southern California shifts to pelagic species and kelp and sand bass, the timing of which is dependent on ocean temperatures. There is more pressure on the rockfish stocks during cold water years.

The business of the recreational fleet is tied to the state of the economy. When fuel prices are high there are fewer boats fishing. Around 2014-2015, as the economy recovered, business started increasing.  Beginning in 2022, the CPFV fleet in southern California made a concerted effort to avoid copper rockfish grounds, and when copper rockfish were encountered, encouraged their clients to release and descend copper rockfish back to depth. Anglers who were not catching as many fish were more interested in retaining their copper rockfish.

In general, there is less rocky habitat in southern California compared to northern California. In southern California towards San Diego, coppers are typically found in less than 35 fm with juveniles in less than 10 fm. In some areas, size classes of coppers are mixed and are not caught deeper than 60 fm.

A portion of the U.S. fleet fishes rockfish in Mexican waters where there are some known areas of higher copper rockfish density. At the Coronado Islands in Mexico, coppers are typically found in 28-35 fm on low-relief habitat. Fishing is more consistent in Mexican waters.

The activity of private vessels is dependent on ocean conditions, the vessel's size, range and fuel costs. Private vessels of >25 ft are usually focused on pelagic species and may fish rockfish during the transit to or from highly migratory species grounds.  It's difficult for the private anglers to access offshore waters at depths of 50+ fm.



### Additional Notes of Interest

Some of the meeting attendees participate in Cooperative Research, such as the NWFSC and the CCFRP Hook and Line surveys and the SWFSC Cooperative Sampling Program.

During the NWFSC Hook and Line survey, there have been times when the vermilion and widow rockfishes are abundant and the lines are reeled in before even reaching the bottom where copper rockfish may be encountered. Anglers who previously participated in ROV studies with NMFS observed rockfish species moving to the bottom and hiding in crevices when the ground swell reached 6-7 ft. There is interest in participation in future ROV surveys.  

We heard interest from the CPFV fleet in deploying conductivity, temperature, and depth (CTD) devices during their trips. Fishermen are interested in tagging fish they release.

The number one question posed to the STAT at all meetings was, "How will the stock assessment account for closed areas?" The fleet would like to see some accounting for these areas in the assessment models.